govuk-one-login/mobile-id-check-async

.github/hook-scripts/pre-commit
.github/workflows/async-credential-pull-req.yml
README.md
src/functions/asyncCredential/asyncCredentialHandler.test.ts
src/functions/asyncCredential/asyncCredentialHandler.ts
src/functions/asyncToken/asyncTokenHandler.test.ts
src/functions/asyncToken/asyncTokenHandler.ts
src/functions/asyncToken/clientCredentialsService/clientCredentialsService.test.ts
src/functions/asyncToken/clientCredentialsService/clientCredentialsService.ts
src/functions/asyncToken/requestService/requestService.test.ts
src/functions/asyncToken/requestService/requestService.ts
src/functions/asyncToken/ssmService/ssmService.test.ts
src/functions/asyncToken/ssmService/ssmService.ts
src/functions/asyncToken/tokenService/tokenService.test.ts
src/functions/asyncToken/tokenService/tokenService.ts
src/functions/config.ts
src/jest.config.ts
src/package-lock.json
src/package.json

- Added Pretter formatter to dev dependencies
- Created scripts for checking and fixing formatting
To have consistent formatting

DCAMW-8264: Add Prettier for formatting code

---

.github/workflows/async-credential-pull-req.yml
.github/workflows/async-credential-push-to-main.yml

​
Changed paths on GHA workflows
To allow PR checks and main branch merge workflows to run when any file changes in src

DCMAW-8264 Changed paths on GHA workflows

---

.github/hook-scripts/pre-commit
src/functions/asyncCredential/asyncCredentialHandler.test.ts
src/functions/asyncCredential/asyncCredentialHandler.ts

Add validation to check that the redirect_uri parameter in the request body is a valid URL for the credential lambda

DCMAW-8264: Check redirect_uri is a valid URL

---

.github/workflows/async-credential-push-to-main.yml
README.md

DCMAW-8264
​
Adds sonar and GHA status badges to the README.md
Update post-merge GHA so sonar main branch analysis has a fetch-depth of 0
Clear visibility of status
Sonar has extra info to do the scan (e.g. git blame info)

DCMAW-8264: Sonar updates

---

.github/pull_request_template.md
src/functions/asyncCredential/asyncCredentialHandler.test.ts
src/functions/asyncCredential/asyncCredentialHandler.ts
src/functions/asyncCredential/registeredLogs.ts

Log when authorization header is missing or incorrectly formatted.
Observability

DCMAW-8264: Logs when authorization header is invalid

---

src/functions/asyncCredential/asyncCredentialHandler.test.ts
src/functions/asyncCredential/asyncCredentialHandler.ts
src/functions/asyncCredential/sessionService/sessionService.test.ts
src/functions/asyncCredential/sessionService/sessionService.ts

- Renamed service dealing with session recovery (and now creation) to called SessionService
- Created new function is SessionService class to create new session
Following tech design [here](https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/3917447301/Strategic+App+DCMAW-7690+Implementing+Client+Credentials+Grant+Flow+and+Asynchronous+CRI+credential+requests) to create async credential lambda
DCMAW-8264

DCMAW-8264: Session service created

---

backend-api/src/functions/asyncCredential/asyncCredentialHandler.ts

​DCMAW-9802
Reduces the length of the lambda function by extracting authorization header validation into one function

DCMAW-9802: Refactor authorization header validation

---

backend-api/src/functions/asyncCredential/asyncCredentialHandler.test.ts
backend-api/src/functions/asyncCredential/asyncCredentialHandler.ts
backend-api/src/functions/services/clientCredentialsService/clientCredentialsService.test.ts
backend-api/src/functions/services/clientCredentialsService/clientCredentialsService.ts

​DCMAW-9802
Groups all request validation within one function to reduce the length of the /async/credential Lambda.

DCMAW-9802: Refactor request body validation for the async credential lambda

---

backend-api/src/functions/asyncCredential/asyncCredentialHandler.test.ts
backend-api/src/functions/asyncCredential/asyncCredentialHandler.ts

​DCMAW-9802
Return 500 internal server error when failing to write audit event
Bug

DCMAW-9802: Error when failing to write session created event

---

infra/templates/kms/template.yaml

Ticket: https://govukverify.atlassian.net/browse/DCMAW-9808
Adding supporting infra for the backend api stack. This will include templates for the platform supporting stacks which aren't provided by devplatform

[DCMAW-9808] Adding supporting infra

---

.github/workflows/backend-api-push-to-main.yml

​DCMAW-9786
Fix typo in backend-api push to main workflow
bugfix

DCMAW-9786: fix typo in cosign gha step

---

.github/workflows/backend-api-push-to-main.yml

​DCMAW-9786
Remove cosigning of test image in dev
Permission failures - needs further investigating

DCMAW-9786: Comment out cosign step from workflow

---

backend-api/infra-tests/application.test.ts
backend-api/template.yaml

​DCMAW-9786
Remove the arn nomenclature 
AWS populates this automatically

DCMAW-9786: Fix iam role name

---

.github/workflows/backend-api-push-to-main.yml

​DCMAW-9786
Adds ECR login to to push to main backend-api pipeline
Give permissions to push to AWS ECR

DCMAW-9786: Login to ECR befoer pushing build image

---

sts-mock/template.yaml

​DCMAW-8964
Adds code signing blocks within SAM template.
This is part of ongoing attempts to fix an STS pipeline error.

DCMAW-8964: Add code signing properties to template sections

---

backend-api/template.yaml

​DCMAW-8456
Add environment suffix to jwks bucket
S3 bucket names are globally unique

DCMAW-8456: Add environment suffix to jwks bucket

---

backend-api/src/functions/asyncCredential/sessionService/sessionService.ts
backend-api/template.yaml

​DCMAW-10100
- Provides permission to query session table index
- Updates session table schema
- Fixes to query command found since deploying to AWS
Ongoing create session work
-  [x] There is a ticket raised for this PR that is present in the branch name

DCMAW-10100: Updates session table schema, permissions and query

---

backend-api/template.yaml

​DCMAW-10100
Adds name to session table in template.yaml

DCMAW-10100: Adds name to session table resource

---

.github/workflows/backend-api-push-to-main.yml

​DCMAW-10218
See here: https://github.com/govuk-one-login/mobile-id-check-async/pull/143
Bug in latest commit - https://gds.slack.com/archives/C02U78Y5J3H/p1726220823459709

DCMAW-10218: Roll back dev platform upload GHA bump

---

backend-api/src/functions/asyncToken/asyncTokenHandler.test.ts
backend-api/src/functions/asyncToken/requestService/requestService.ts

​DCMAW-10208
Updated parsing of body from expecting a JSON to expecting application/x-www-form-urlencoded
Defect

DCMAW-10208: Update token handler to use correct response body schema

---

.github/workflows/backend-api-pull-request.yml
.github/workflows/backend-api-push-to-main.yml
backend-api/sonar-project.properties

​DCMAW-10222
Move sonar properties file inside the backend-api directory
To enable other stacks to more easily set up Sonar

DCMAW-10222: move sonar properties file

---

sts-mock/template.yaml

Reverts govuk-one-login/mobile-id-check-async#179

Revert "fix: change TokenFunctionRole name temporarily"

---

infra/terraform/secure_pipelines/mob_sts_mock_pipeline.tf

​DCMAW-10369
Relocated count conditional.
Terraform configuration was deleting the sts-mock-pl stack in Dev
Evidence:
Running Terraform Plan in Dev:
Ran in Staging to confirm previous issue no longer exists also:

[DCMAW-10369] fix count conditional to fix pipeline deployments

---

backend-api/src/functions/asyncCredential/asyncCredentialHandler.ts
backend-api/src/functions/asyncToken/asyncTokenHandler.ts
backend-api/tests/api-tests/clientCredentialsGrantFlow.test.ts

​DCMAW-8389
- Add some temporary logs
- Debug why private API tests are failing in the pipeline

DCMAW-8389: add temporary logs to debug

---

backend-api/src/functions/services/events/eventService.ts
backend-api/tests/api-tests/clientCredentialsGrantFlow.test.ts

​DCMAW-8389
- Add more temporary debug logs
- To investigate API test failure

DCMAW-8389: add more debug logs to investigate API test failure

---

backend-api/tests/api-tests/clientCredentialsGrantFlow.test.ts

​DCMAW-8389
- Some minor refactoring in `clientCredentialsGrantFlow.test.ts`
- To improve readability

DCMAW-8389: make APIs in test logic nicer

---

backend-api/template.yaml

Restores sessions table name
Reverts govuk-one-login/mobile-id-check-async#220

Revert "[DCMAW-10280] restore sessions table to see if it will fix deployments"

---

backend-api/run-tests.sh

​DCMAW-8229
To enable API tests to pass in the pipeline

DCMAW-8229: add sts mock api url env var to run-tests script

---

backend-api/tests/api-tests/activeSession.test.ts

DCMAW-8229: add api tests

---

.github/workflows/test-resources-push-to-main.yml

​DCMAW-10737
Adds test-resources-push-to-main.yml GitHub Actions workflow with Sonar scan step for test-resources directory
To ensure that changes made to the test-resources directory pass quality checks when merging to main.

DCMAW-10737: Add post-merge GH Actions workflow with Sonar scan for test-resources directory

---

README.md

​DCMAW-10782
Updated the Readme to include a reference to the DCMAW CRI
Feedback from this PR: https://github.com/govuk-one-login/mobile-android-cri-orchestrator/pull/22#discussion_r1872918286

DCMAW-10782: add DCMAW keyword to readme

---

.github/workflows/backend-api-pull-request.yml

Reverts govuk-one-login/mobile-id-check-async#285

Revert "DCMAW-10772: add permissions to workflow"

---

backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

Adds high and low threshold alarms for `4XX` and `5XX` errors on the `async/biometricToken` endpoint
Alarm configuration requirements can be found on the ticket
System monitering
Status: In progress
Status: In progress
Deployed stack and intentionally caused `4XX` and `5XX` errors to ensure the alarms triggered correctly

DCMAW-9076: Creates 4xx and 5xx alarms for /async/biometricToken endpoint

---

backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

​DCMAW-11138
Defines the STS Base URL in Staging/Integration/Production. 
Required for integration testing in Staging and will be required when going live.

DCMAW-11138: Define STS URL in higher envs

---

.github/hook-scripts/pre-commit
backend-api/README.md
backend-api/combine_template.sh
backend-api/infra/README.md
backend-api/infra/api/private.yaml
backend-api/infra/api/proxy.yaml
backend-api/infra/api/sessions.yaml
backend-api/infra/functions/activeSession.yaml
backend-api/infra/functions/biometricToken.yaml
backend-api/infra/functions/credential.yaml
backend-api/infra/functions/jwks.yaml
backend-api/infra/functions/proxy.yaml
backend-api/infra/functions/token.yaml
backend-api/infra/kms/keys.yaml
backend-api/infra/monitoring/alarms.yaml
backend-api/infra/parent.yaml
backend-api/infra/queue/txma.yaml
backend-api/infra/storage/jwks.yaml
backend-api/infra/storage/session.yaml
backend-api/package.json
backend-api/template.yaml
backend-api/tests/infra-tests/template.test.ts
backend-api/tests/testUtils/testFunctions.ts
sts-mock/package-lock.json
sts-mock/package.json

​DCMAW-10844
Split master template.yaml file into smaller subfiles and created shell script to bundle it together again.
To make template more manageable

[DCMAW-10844] Organise async backend resources into sub-templates

---

sts-mock/package-lock.json

​DCMAW-11057
package.json and package-lock.json have drifted.
npm ci/clean-install, which is used in #338 relies on the package-lock.json and package.json being in sync. They should also be in sync at all times in any case.

DCMAW-11057: Rebuild sts-mock package-lock.json

---

.github/workflows/job-build-and-push-test-image.yml
.github/workflows/sts-mock-push-to-main.yml
sts-mock/Dockerfile
sts-mock/run-tests-locally.sh
sts-mock/run-tests.sh

Includes the original commit onto main introduced in #338. It can now be merged following a fix to the sts-mock package-json.lock #361 
Previously reverted. See #338

DCMAW-11057: Re-apply changes to push STS test image to Dev and Build

---

.github/workflows/sts-mock-push-to-main.yml

​DCMAW-11057
Fix for https://github.com/govuk-one-login/mobile-id-check-async/actions/runs/12951355093/job/36126276521
Updates .nvmrc directory used in the Github actions to include sts-mock/
Breaking GHA

DCMAW-11057: Fix sts-mock GHA - .nvmrc path 

---

sts-mock/infra/dequeue/api.yaml
sts-mock/template.yaml

DCMAW-11006: Update SSM Reference for Events certificate

---

test-resources/run-tests-locally.sh

DCMAW-11006: Update default stack name for run-tests-locally file

---

.github/CODEOWNERS

​DCMAW-11492
#406 incorrectly modified the heirarchy of the Codeowners file. This fixes it by ensuring the heirarchy of approval goes from top to bottom; as the file is read downwards, permissions can be superseeded.

DCMAW-11492: Fix codeowners file

---

backend-api/tests/api-tests/finishBiometricSession.test.ts

​DCMAW-11108
Updated a variable in the tests
To fix the pipeline as incorrect variable used

DCMAW-11108 | POST async/finishBiometricSession request body validation | HOTFIX

---

.github/workflows/backend-api-pull-request.yml
.github/workflows/backend-api-push-to-main.yml
.github/workflows/job-build-and-push-test-image.yml
.github/workflows/test-resources-pull-request.yml
.github/workflows/test-resources-push-to-main.yml

Reverts govuk-one-login/mobile-id-check-async#430

Revert "Bump the gha-version group across 1 directory with 3 updates"

---

backend-api/tests/api-tests/biometricToken.test.ts
backend-api/tests/api-tests/clientCredentialsGrantFlow.test.ts
backend-api/tests/api-tests/utils/apiTestHelpers.ts
backend-api/tests/infra-tests/application.test.ts

​DCMAW-11007
This PR adds:
- TxMA assertions the following events:
- `DCMAW_ASYNC_CRI_START`
- `DCMAW_ASYNC_CRI_4XXERROR`
- Infra tests for `EventsBaseUrl`s

DCMAW-11007: Add TxMA assertions to API tests

---

backend-api/infra/parent.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

[​DCMAW-11909](https://govukverify.atlassian.net/browse/DCMAW-11909)
Updates the IPVCore VPCe ID for staging.

[DCMAW-11909] update VPC endpoint ID for IPVCore integration

---

backend-api/infra/deployment/config.yaml
backend-api/infra/functions/activeSession.yaml
backend-api/infra/functions/biometricToken.yaml
backend-api/infra/functions/credential.yaml
backend-api/infra/functions/finishBiometricSession.yaml
backend-api/infra/functions/token.yaml
backend-api/infra/monitoring/canaryAlarms.yaml
backend-api/infra/parent.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

[​DCMAW-11435](https://govukverify.atlassian.net/browse/DCMAW-11435)
- Add conditionals
- creates service role and deployment config
This has been tested by deploying the code then making a change to the credentials lambda function. The deployment began by moving 20% per minute. Then we invoked the lambda until it set off one of the alarms. The deployment then rolled back to the original lambda version.

[DCMAW-11435] Configure canary deployments

---

backend-api/tests/infra-tests/application.test.ts

​DCMAW-12012
Fixes broken infra test

[DCMAW-12012] fix error in infra test

---

.github/pull_request_template.md

DCMAW-11451
Updating the PR template to better reflect what the web engineers have agreed what they would like to see when raising a PR.
<details>
- **Readability**: Is …

DCMAW - 11451: Updating PR Template

---

backend-api/src/functions/services/clientRegistryService/clientRegistryService.ts

​DCMAW-12000
Temporarily log clientId in request before it is compared for IPV request debugging

DCMAW-12000: Temporarily log clientId in in token lambda for IPV request debugging

---

backend-api/infra/api/private.yaml
backend-api/template.yaml

DCMAW-12000
always deploy for private api

DCMAW-12000: add always deploy

---

backend-api/infra/monitoring/sqsAlarms.yaml
backend-api/infra/queue/vendorProcessing.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

​DCMAW-11339
- Creates 1 alarm for the Vendor Processing SQS queue and 3 alarms for the Vendor Processing SQS DLQ.
- Updates tests to cover new alarms
- Corrects error on DLQ. Provides correct KMS key alias
- Updates [runbook](https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/4800446694/Alarms+Runbook+Warnings) (in progress)
This has been tested. Changed alarm to trigger after 2 mins. Messages added to queue and DLQ, triggered 3 of the 4 alarms (sqs queue has message for longer than 2 mins, dlq has new message, dlq has message for longer than 2 mins - didn't bother with the high threshold one)

[DCMAW-11339] SQS queue and DLQ alarms

---

backend-api/infra/functions/token.yaml
backend-api/infra/parent.yaml
backend-api/src/functions/asyncToken/requestService/requestService.ts
backend-api/src/functions/services/clientRegistryService/clientRegistryService.ts
backend-api/template.yaml

DCMAW-12000
Logs the Authorization header in the asyncTokenHandler. This is a `debug` log and the lambda LogLevel config has been updated to include logs at this level.
Note this is a temporary change to support debugging a failing request when invoked by the IPVCore web triage pages in Staging. This PR will be reverted following testing.
<details>
- **Security Considerations**: Are there any security implications that need to be …

DCMAW-12000: Add debug log for async token authorization header

---

.github/workflows/job_ci-checks.yml
.github/workflows/job_sonarqube.yml
.github/workflows/job_test-suite.yml

DCMAW-12116
Creates 3 new reusable jobs; ci-checks, test suite, and sonarqube checks.
The new PR will use these three jobs for the test resources pull request workflow --> https://github.com/govuk-one-login/mobile-id-check-async/pull/498
<details>
- **Testing**: Is the code well-tested with sufficient coverage to provide confidence in …

DCMAW-12116: create reusable jobs for testing, ci checks, and sonarQube

---

.github/workflows/test-resources-pull-request.yml

DCMAW-12116
Creates 3 new reusable jobs; ci-checks, test suite, and sonarqube checks. Test-resource pull request workflow uses these jobs to run PR checks when a PR is in ready to review. Workflow can be run manually from the actions tab if user wants to test before PR is in ready for review.
<details>
- **Testing**: Is the code well-tested with …

DCMAW-12116: create reusable jobs for pull request workflow for test-resources

---

.github/workflows/job_ci-checks.yml

DCMAW-12116
Fixes little error in formatting step. This should check the formatting rather than making a change to the formatting.
<details>
- **Readability**: Is the …

DCMAW-12116: fix formatting step error

---

.github/pull_request_template.md
helper-scripts/package-lock.json

DCMAW-12117
- This [PR](https://github.com/govuk-one-login/mobile-id-check-async/pull/496) included a commit towards the end where it updated the licence in the `package.json` to be `MIT` to be consistent with other packages however the update to the lock file was not committed.
- Updates minor typo in pull request template
<details>
- …

DCMAW-12117: Updates helper-scripts package lock file, fixes typo in PR template

---

backend-api/infra/functions/token.yaml
backend-api/infra/parent.yaml
backend-api/src/functions/asyncToken/requestService/requestService.ts
backend-api/template.yaml

Reverts govuk-one-login/mobile-id-check-async#495

Revert "DCMAW-12000: Reverts IPVCore debug logs"

---

.github/workflows/backend-api-pull-request.yml
.github/workflows/helper-scripts-pull-request.yml
.github/workflows/job_ci-checks.yml
.github/workflows/job_test-suite.yml
.github/workflows/test-resources-pull-request.yml
.github/workflows/workflow_pull-request.yml

DCMAW-12118
- Creates a reusable workflow for pull request workflow
- Uses workflow for test-resources and backend-api
- Only runs npm scripts if they exist
- Adds conditionals to skip sonarqube scans and not upload to test coverage as artifact
infra PR --> 
<details>
- **Testing**: Is the code well-tested with sufficient coverage to provide …

DCMAW-12118:  Create and use pull request workflow

---

backend-api/src/functions/asyncToken/asyncTokenHandler.test.ts
backend-api/src/functions/asyncToken/requestService/requestService.ts
backend-api/tests/api-tests/clientCredentialsGrantFlow.test.ts

DCMAW-12247
- Updates async/token endpoint to uri decode clientId and clientSecret in request service
- Updates API test to send client creds in request as uri encoded
- I want to update logging to be clearer and proxy through error messages properly
- Remove error type from Result as it's never checked
- Update test structure and wording
<details>
- **Security Considerations**: Are there any security implications that need to be …

DCMAW-12247: Updates async/token endpoint to uri decode clientId and clientSecret

---

backend-api/infra/functions/credential.yaml
backend-api/infra/parent.yaml
backend-api/src/functions/services/session/tests/sessionService.test.ts
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

DCMAW-11220
The `timeToLive` was previously set at one hour so that it could also be used to validate session expiry. In cb4e1d9b3eb5b69ddc72dcd4188da53a8a1c533c we migrated to use the `createdAt` attribute instead. 
We can now update the `timeToLive` to be one day; this matches the live service in higher environments. For dev and build the live service has this set at 7 days; I don't think we need this. If we do, this is a simple change down the line.
Validate that the environment variable is 1 day in seconds please!
<details>
- **Requirements**: Does the code meet functional and non-functional requirements including compliance with programme standards and …

DCMAW-11220: Update Sessions table timeToLive to 1 day

---

backend-api/infra/functions/token.yaml
backend-api/infra/parent.yaml
backend-api/src/functions/asyncToken/requestService/requestService.ts
backend-api/template.yaml

This PR removes the IPVCore debug logs
Reverts govuk-one-login/mobile-id-check-async#513

Revert "Revert "DCMAW-12000: Reverts IPVCore debug logs""

---

backend-api/infra/README.md
backend-api/infra/monitoring/sqsAlarms.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

DCMAW-12115
- Adds alarms for IPV core SQS
- changes naming convention for existing sqs alarms
Runbooks
https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/4800446694/Alarms+Runbook+Warnings
https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/4799594677/Alarms+Runbook+Alerts+-+DRAFT
<details>
- **Testing**: Is the code well-tested …

DCMAW-12115: add IPV Core SQS alarms

---

.github/dependabot.yml

DCMAW-11907
Updates `dependabot.yml` to ignore `jose` package bumps > to `5.X.X` for `backend-api` and `test-resources`.
`jose` has recently released a new major version, `6.X.X`. Due to changes in compatibility re CSJ and ESM (also investigated by IPV core [here](https://github.com/govuk-one-login/ipv-spot/pull/1540)) and also breaking type changes (see [changelog](https://github.com/panva/jose/blob/main/CHANGELOG.md#600-2025-02-22)), this change would require more investigation and work to bump the version. 
Further, jose `5.X.X` will still receive security updates (see [support versions](https://github.com/panva/jose/tree/main?tab=readme-ov-file#supported-versions) confirming this) so we are happy for now to stick with version `5.X.X`
Will create a ticket to eview this package in the …

DCMAW-11907: Updates Dependabot to ignore jose package bumps > to 5.X.X

---

backend-api/infra/functions/activeSession.yaml
backend-api/infra/functions/biometricToken.yaml
backend-api/infra/functions/credential.yaml
backend-api/infra/functions/finishBiometricSession.yaml
backend-api/infra/functions/token.yaml
backend-api/infra/monitoring/canaryAlarms.yaml
backend-api/infra/parent.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

DCMAW-12384
Creates and uses new condition for canary alarms. New condition will only deploy and attach canary alarms if DeployAlarms is true and lambda deployment config isn't set to AllAtOnce.
<details>
- **Edge Cases**: Have edge cases been …

DCMAW-12384: add canary alarm condition

---

backend-api/infra/monitoring/alarms.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

DCMAW-11274
Adds 4 alarms for abortSession.
Runbooks have been updated
- https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/4800446694/Alarms+Runbook+Warnings
- https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/4799594677/Alarms+Runbook+Alerts+-+DRAFT
<details>
- **Testing**: Is the code well-tested with sufficient coverage to …

DCMAW-11274: Add 4XX and 5XX alarms for abortSession

---

backend-api/src/functions/asyncIssueBiometricCredential/asyncIssueBiometricCredentialHandler.test.ts
backend-api/src/functions/asyncIssueBiometricCredential/asyncIssueBiometricCredentialHandler.ts
backend-api/src/functions/asyncIssueBiometricCredential/validateSqsEvent.ts
backend-api/src/functions/common/logging/LogMessage.ts

DCMAW-12112
- Adds validation logic to `issueBiometricCredential` lambda to check `SQSEvent` to ensure it contains 1 `Record` which contains a `sessionId` in the shape for a `UUID v4`
- If validation fails, logs and exits
- If validation succeeds:
- Appends `sessionId` to `logger`
- Logs `COMPLETED` message and exit
- Alarms
Deployed stack and ran API tests. This triggered `finishBiometricSession` to send a message to the `vendorProcessing Queue`, which in turn triggered the `issueBiometricCredential` lambda. Viewed logs for `issueBiometricCredential` in `CloudWatch` and confirmed I saw the STARTED and COMPLETED logs
I want to re deploy a stack that has finishedBiometricSession send an invalid message to the vendorProcessingQueue to ensure the lambda deals with this correctly
<details> …

DCMAW-12112: Validates inbound message payload in issueBiometricCredential Lambda

---

test-resources/run-tests.sh

DCMAW-12374
Pipelines failed on the test stage. The test resources api url environment variable was not set.
Evidence: 
<details>
- **Readability**: Is the code easy to …

DCMAW-12374: fix test-resources run-tests.sh

---

.github/workflows/backend-api-push-to-main.yml
.github/workflows/test-resources-push-to-main.yml

DCMAW-12160
Remove old SAM CLI version from workflow as it does not work with Node 22
Remove blank spaces in workflows

[DCMAW-12160] remove SAM cli version from dev push to main job

---

.github/workflows/job_ci-checks.yml
.github/workflows/job_test-suite.yml
.github/workflows/workflow_pull-request.yml

DCMAW-12114
This PR adds conditional inputs to the pull request workflow. This is needed for the pull request workflow in the mobile-id-check-biometric-credential repo --> https://github.com/govuk-one-login/mobile-id-check-biometric-credential/pull/1
<details>
- **Testing**: Is the code well-tested with sufficient coverage to provide confidence …

DCMAW-12114: update workflows

---

backend-api/infra/parent.yaml
backend-api/template.yaml

DCMAW-12181
Allows promotion of pipeline to integration
<details>
- **Readability**: Is the code easy to understand for all team members, with clear naming and …

DCMAw-12181: Allow backend-api to be promoted to integration

---

backend-api/infra/functions/issueBiometricCredential.yaml
backend-api/template.yaml

Reverts govuk-one-login/mobile-id-check-async#579

Revert "DCMAW-12181: Move SQS trigger inline to fix deployment"

---

backend-api/infra/parent.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

DCMAW-12181
The issueBiometricCredentialHandler reserved concurrency is set to 0 in Integration.
The event source mapping (lambda trigger) has a maximum scaling concurrency of 34. 
The deployment to integration fails as the event source mapping concurrency cannot be higher than the lambda's reserved concurrency. The event source scaling concurrency has to also be >=2. This means it can not be set to 0
This PR sets the issueBiometricCredentialHandler concurrency in Integration to 34 (the target production value). Given this lambda is not invoked synchronously, it is still effectively disabled
<details>
- **Requirements**: Does the code meet functional and …

DCMAW-12181: Enable issueBiometricCredentialHandler concurrency in int

---

backend-api/infra/functions/jwks.yaml
backend-api/template.yaml

DCMAW-12181
Sets reserved concurrency to 1 on the JWKS custom resource in all environments to fix deployment into Integration. 
The lambda has to execute successfully for Code Pipeline to deploy the application. Reserved concurrency was previously 0 (inherited from lambda globals).
<details>
- **Testing**: Is the code well-tested with sufficient …

DCMAW-12181: Set jwks handler reserved concurrency

---

backend-api/infra/api/proxy.yaml
backend-api/infra/parent.yaml
backend-api/template.yaml

DCMAW-13091
Changes resource policy to allow perf testers IAM role access to our proxy api.
<details>
- **Readability**: Is the code easy to understand for all team …

DCMAW-13091: allow perf testers vpc access to proxy api

---

backend-api/infra/functions/issueBiometricCredential.yaml
backend-api/src/functions/adapters/aws/sqs/types.ts
backend-api/src/functions/asyncAbortSession/asyncAbortSessionHandler.test.ts
backend-api/src/functions/asyncIssueBiometricCredential/RetainMessageOnQueue.ts
backend-api/src/functions/asyncIssueBiometricCredential/asyncIssueBiometricCredentialHandler.test.ts
backend-api/src/functions/asyncIssueBiometricCredential/asyncIssueBiometricCredentialHandler.ts
backend-api/src/functions/asyncIssueBiometricCredential/handlerDependencies.ts
backend-api/src/functions/common/session/updateOperations/ResultSent/ResultSent.test.ts
backend-api/src/functions/common/session/updateOperations/ResultSent/ResultSent.ts
backend-api/src/functions/testUtils/unitTestData.ts
backend-api/template.yaml

DCMAW-12523
- Writes VC to the IPVCore outbound SQS
- Updates Dynamo session state
- Error handling for the above two scenarios
Note: using the new test harness will come on a follow-up PR - there is a ticket for this in the next sprint.
- **Edge Cases**: Have edge cases been …

DCMAW-12523: Write VC to outbound queue and update session state

---

backend-api/infra/api/proxy.yaml
backend-api/infra/api/sessions.yaml
backend-api/template.yaml
test-resources/infra/common/api.yaml
test-resources/infra/dequeue/api.yaml
test-resources/infra/sts-mock/token/api.yaml
test-resources/template.yaml

DCMAW-13116
- Removes `DependsOn` from record set and base path mapping resources
- Updates the `Name` property in record set resources to reference the domain name resource
- Updates the `DomainName` property in base path mapping resources to reference the domain name resource
<details>
- **Testing**: Is the code well-tested with sufficient …

DCMAW-13116: implicit dependencies for base path mapping

---

backend-api/src/functions/common/session/updateOperations/BiometricSessionFinished/BiometricSessionFinished.test.ts
backend-api/src/functions/common/session/updateOperations/BiometricSessionFinished/BiometricSessionFinished.ts
backend-api/tests/api-tests/finishBiometricSession.test.ts

DCMAW-12227
* Updates FinishBiometricSession update operation to only validate for base session attributes on a conditional check failure where an item is present, since we cannot guarantee which invalid state the session is in
* _Replaces_ session not found API test with API test for this scenario. As per our dev time testing discussions, given sufficient unit test coverage we don't need more than one API test for each different response mode/AWS interaction, and of the two 401 tests this one gives us better verification of our state machine.
<details>
- **Requirements**: Does the code meet functional and non-functional requirements including compliance with …

[DCMAW-12227] Validate for base session attributes when FinishBiometricSession update fails

---

backend-api/infra/api/private.yaml
backend-api/infra/parent.yaml
backend-api/template.yaml
backend-api/tests/api-tests/abortSession.test.ts
backend-api/tests/infra-tests/application.test.ts
backend-api/tests/infra-tests/template.test.ts

DCMAW-12527
Adds performance prod account's execute-api VPCe to our private API config. This change:
1) Creates a DNS record (EndpointConfiguration)
2) Allows resources from their VPC to access the Private API
<details>
- **Edge Cases**: Have …

DCMAW-12527: Add performance test vpce to private api

---

backend-api/infra/parent.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

DCMAW-12184
* Updates burst and rate limits for the sessions, private and proxy (to match private) API-GWs, in line with the ticket values.
* Updates associated infra tests.
<details>
- **Edge Cases**: Have edge cases been considered and handled …

[DCMAW-12184] Update non-prod API rate limits

---

backend-api/infra/monitoring/alarms.yaml
backend-api/infra/monitoring/metrics.yaml
backend-api/package-lock.json
backend-api/package.json
backend-api/src/functions/asyncCredential/asyncCredentialHandler.test.ts
backend-api/src/functions/asyncCredential/asyncCredentialHandler.ts
backend-api/src/functions/asyncIssueBiometricCredential/asyncIssueBiometricCredentialHandler.test.ts
backend-api/src/functions/asyncIssueBiometricCredential/asyncIssueBiometricCredentialHandler.ts
backend-api/src/functions/common/logging/LogMessage.ts
backend-api/template.yaml

DCMAW-12526
- Updates `mobile-id-check-biometric-credential` package from `1.0.0` to `1.1.0`
- Add log message `MOBILE_ASYNC_ISSUE_BIOMETRIC_CREDENTIAL_VC_ISSUED` and log with `documentType`
- Adds metric filters to capture when a session is created and when a VC is issued
- `JourneyStartedMetricFilter`
- `CredentialsIssuedMetricFilter`
<details>
- **Security Considerations**: Are there any security implications that need to be …

DCMAW-12526: Add VC issued log with documentType value

---

backend-api/infra/parent.yaml
backend-api/infra/queue/ipvCore.yaml
backend-api/infra/queue/txma.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

DCMAW-13310
Adding names to our SQS queues. This will be done in 3 steps (add/switch/remove). 
This is stage 1, adding new queues and policies with correct names
<details>
- **Edge Cases**: Have edge cases been considered and handled …

DCMAW-13310: add QueueName to sqs queues

---

backend-api/infra/functions/credential.yaml
backend-api/infra/functions/jwks.yaml
backend-api/infra/functions/token.yaml
backend-api/infra/parent.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

DCMAW-12185
- **Added**: Individual Lambda concurrency mappings for AsyncToken, AsyncCredential, and JsonWebKeys functions
- **Added**: Test coverage for AsyncToken, AsyncCredential, and JsonWebKeys lambda concurrency settings
- **Changed**: AsyncTokenFunction to use mapped concurrency values (dev: 0, build: 160, staging: 15, integration: 15, production: 0)
- **Changed**: AsyncCredentialFunction to use mapped concurrency values (dev: 0, build: 160, staging: 15, integration: 15, production: 0)
- **Changed**: JsonWebKeysFunction to use mapped concurrency value (1 for all environments) instead of hard-coded value
- **Changed**: Lambda mapping to include specific concurrency settings for individual functions
- **Changed**: Spelling of lamba -> lambda
- **Removed**: Hard-coded concurrency …

DCMAW-12185: Update lambda concurrency in non-prod environments

---

backend-api/infra/parent.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

DCMAW-12021
Adds IPVCore's VPCe to the Private APIgw resource policy. This allows IPVCore to make requests to the API.
<details>
- **Readability**: Is the code easy to …

DCMAW-12021: Add IPVCore to Private ApiGw policy in higher envs

---

backend-api/infra/parent.yaml
backend-api/template.yaml

DCMAW-12021
Updates Cloudformation condition to add the IPVCore VPCe to the API resource policy. The config was previously updated https://github.com/govuk-one-login/mobile-id-check-async/pull/646 but the resource policy was not updated due to a CFN conditional. This fixes the conditional
<details>
- **Testing**: Is the code well-tested with …

DCMAW-12021 fix API resource policy in int/prod

---

backend-api/infra/parent.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

DCMAW-12925
Updates Sessions API config for Prod:
- `ApiBurstLimit` updated from `0` to `400`
- `ApiRateLimit` updated from `0` to `200`
<details>
- **Readability**: Is …

DCMAW-12925: Update Sessions API rate and burst limits in Prod

---

backend-api/infra/monitoring/alarms.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

DCMAW-12521
Adds alarms:
- `AsyncIssueBiometricCredentialParseFailureLowThresholdAlarm`
- `AsyncIssueBiometricCredentialParseFailureHighThresholdAlarm`
- `AsyncIssueBiometricCredentialVendorLikenessDisabledAlarm`
- `AsyncIssueBiometricCredentialBiometricSessionNotValidLowThresholdAlarm`
- `AsyncIssueBiometricCredentialBiometricSessionNotValidHighThresholdAlarm`
<details>
- **Security Considerations**: Are there any security implications …

DCMAW-12521: Add BiometricCredential error alarms

---

backend-api/infra/monitoring/alarms.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

DCMAW-12099
Adds `async-issue-biometric-credential-zero-vcs-issued` critical alarm
Warning:
[https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/4800446694/Alarm+Runbook+Warnings#:~:text=if%20the%20root%20[…]%2Dthreshold%2Dasync%2Dtxma](https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/4800446694/Alarm+Runbook+Warnings#:~:text=if%20the%20root%20cause%20cannot%20be%20determined.-,mob%2Dasync%2Dbackend%2Dlow%2Dthreshold%2Dasync%2Dissue%2Dbiometric%2Dcredential%2Derror%2Dwriting,to%20tech%20lead%2C%20including%20if%20the%20root%20cause%20cannot%20be%20determined.,-mob%2Dasync%2Dbackend%2Dlow%2Dthreshold%2Dasync%2Dtxma)
Critical:
[https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/4799594677/Alarm+Runbook+Critical+Alerts#:~:text=cannot%20be%20d[…],-IPV%20Core%20Outbound](h …

DCMAW-12099: Add 'zero VCs issued' alarm

---

backend-api/infra/monitoring/throttleAlarms.yaml
backend-api/infra/parent.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

DCMAW-12020
Creates alarms that trigger if lambdas throttle
Runbook - > https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/4799594677/Alarm+Runbook+Critical+Alerts
<details>
- **Edge Cases**: Have edge cases been considered and handled …

DCMAW-12020: lambda throttle alarms

---

backend-api/infra/monitoring/concurrencyAlarms.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

DCMAW-13336
Create new alarm for ClaimedAccountConcurrency metric.
Update tests for new alarm.
[Attempt to update runbook.](https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/4800446694/Alarm+Runbook+Warnings)
<details>
- **Edge Cases**: …

[DCMAW-13336] Create new claimed account concurrency alarm

---

backend-api/src/functions/asyncAbortSession/asyncAbortSessionHandler.test.ts
backend-api/src/functions/common/errors/errorHandlers.ts

DCMAW-12556
- **Updated**: `errorHandler.ts` and changed `suspected_fraud_signal` to `undefined`
- **Updated**: Unit test checking for fraud signal
<details>
- …

DCMAW-12556: Fix async/abortSession incorrectly writing fraud signal into TxMA event

---

backend-api/tests/api-tests/txmaEvent.test.ts

DCMAW-13590
Issue: The pipeline was failing because it couldn't resolve the folder location for the txmaBillingEvents array in events/types, so I pulled it out and put it in the test file itself
- **Added**: Explicit definition of `txmaBillingEvents` array within txmaEvent.test.ts
<details>
- **Testing**: Is the code well-tested with sufficient …

DCMAW-13590-hotfix: Hotfixing issue with pipeline deployment in DCMAW-13590

---

test-resources/infra/parent.yaml
test-resources/infra/sts-mock/token/function.yaml
test-resources/template.yaml
test-resources/tests/infrastructure-tests/application.test.ts

DCMAW-13943
Updates Build environment config:
- Burst limit: `400`
- Rate limit: `200`
- ReservedConcurrency: `160`
<details>
- **Readability**: Is the code easy to …

DCMAW-13943: Update rate limits and reserved concurrency for STS Mock /token endpoint

---

backend-api/infra/resources/async/issueBiometricCredential/alarms.yaml
backend-api/package-lock.json
backend-api/package.json
backend-api/template.yaml

DCMAW-13111
- Updates `AsyncIssueBiometricCredentialDrivingLicenceExpiredAlarm` threshold from `5` to `1`
- Upgrades `@govuk-one-login/mobile-id-check-biometric-credential` package to version `1.1.8`
<details>
- **Edge Cases**: Have edge cases …

DCMAW-13111: Update expired driving licence alarm threshold

---

backend-api/infra/resources/async/issueBiometricCredential/function.yaml
backend-api/template.yaml

DCMAW-14193
Removes `AsyncIssueBiometricCredentialErrorRateAlarm` from list of alarms that would trigger a canary rollback
<details>
- **Readability**: Is the code easy …

DCMAW-14193: Stops Issue Biometric Credential error rate alarm from triggering canary rollback

---

.github/CODEOWNERS

[DCMAW-14243](https://govukverify.atlassian.net/browse/DCMAW-14243)
<details>
- **Readability**: Is the code easy to understand for all team members, with clear naming …

DCMAW-14243: remove SRE team from codeowners

---

backend-api/infra/resources/sessionsApi/abortSession/alarms.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

DCMAW-14329
Updates AsyncAbortSession4XXHighThresholdAlarm to be warning
<details>
- **Readability**: Is the code easy to understand for all team members, with clear …

DCMAW-14329: Updates AsyncAbortSession4XXHighThresholdAlarm to be warning

---

backend-api/infra/resources/sessionsApi/finishBiometricSession/function.yaml
backend-api/template.yaml

DCMAW-14331
<details>
- **Readability**: Is the code easy to understand for all team members, with clear naming and appropriate documentation?
- **Maintainability**: Is …

[DCMAW-14331] Remove low completion alarms from finishBiometricSession canary config

---

backend-api/infra/resources/common/sessionRegistry.yaml
backend-api/template.yaml

DCMAW-14215
- Creates new `GSI` in sessions table called `subjectIdentifier-createdAt-index-v2`
- Has all the same attributes as `subjectIdentifier-createdAt-index` but with the addition of non key attribute `govukSigninJourneyId` in the `Projections` block
- New `GSI` required so `activeSession`'s call to `dynamo` can get access to `govukSigninJourneyId` needed for a new TxMA event
- Decided to add `GSI` separately so there is no time where the index is still filling (which would make calls return `5XX`). Was originally part of [this PR](https://github.com/govuk-one-login/mobile-id-check-async/pull/732) where we are adding new TxMA event
<details>
- …

DCMAW-14215: Creates subjectIdentifier-createdAt-index-v2 GSI in sessions table

---

backend-api/infra/resources/common/sessionRegistry.yaml
backend-api/template.yaml

DCMAW-14215
Removes `subjectIdentifier-createdAt-index` GSI - no longer used. This GSI was replaced with `subjectIdentifier-createdAt-index-v2` in previous commits:
- Adding new GSI [commit](https://github.com/govuk-one-login/mobile-id-check-async/commit/66af06f8811000fed14a0a13c80b146c4af791f3)
- Using new GSI [commit](https://github.com/govuk-one-login/mobile-id-check-async/commit/51dbae9630a57a5a72627a281188bd310342514b)
<details>
- …

DCMAW-14215: Removes subjectIdentifier-createdAt-index GSI - no longer used

---

backend-api/infra/resources/common/sessionRegistry.yaml
backend-api/template.yaml

Reverts govuk-one-login/mobile-id-check-async#743

Revert "DCMAW-14215: Removes subjectIdentifier-createdAt-index GSI - no longer used"

---

test-resources/package-lock.json

DCMAW-14394
run `npm audit fix` to remediate brace-expansion dependabot vulnerability.
<details>
- **Readability**: Is the code easy to understand for all team members, …

DCMAW-14394: fix brace-expansion in test-resources

---

backend-api/infra/resources/async/issueBiometricCredential/alarms.yaml
backend-api/template.yaml

DCMAW-14110
Updates `AsyncIssueBiometricCredentialBiometricSessionNotValidLowThresholdAlarm` `Threshold` from `1` to `4`
> Please see the [ticket](https://govukverify.atlassian.net/browse/DCMAW-14110?focusedCommentId=239183) for the reason for the increase.
<details>
- **Testing**: Is the code well-tested with sufficient coverage to provide …

DCMAW-14110: Update issueBiometricCredential low threshold 'session not valid' alarm config

---

backend-api/infra/resources/sessionsApi/biometricToken/alarms.yaml
backend-api/template.yaml

DCMAW-14373
See ticket for justification of thresholds.
<details>
- **Readability**: Is the code easy to understand for all team members, with clear naming and …

DCMAW-14373: tune biometricToken low threshold 4xx alarm

---

backend-api/infra/resources/sessionsApi/biometricToken/alarms.yaml
backend-api/template.yaml

DCMAW-14373 -> please see ticket for accompanying commentary
Tunes the low completion alarm to be less sensitive given there are known lambda errors driven from client behaviour for which we are OK to ignore (for now)
<details>
- **Edge Cases**: …

DCMAW-14373: Tune asyncBiometricToken low completion alarm

---

backend-api/infra/resources/async/ipvCoreOutboundQueue/queue.yaml
backend-api/template.yaml

DCMAW-14051
Updates IPVCore queue redrive policy `maxReceiveCount` from `60` to `5`
<details>
- **Readability**: Is the code easy to understand for all team members, …

DCMAW-14051: Updates IPVCore queue redrive policy maxReceiveCount from 60 to 5

---

backend-api/infra/resources/sessionsApi/abortSession/alarms.yaml
backend-api/template.yaml

DCMAW-14348
- Updates `AsyncAbortSession4XXLowThresholdAlarm` `DatapointsToAlarm` from `2` to `3`
- Updates `AsyncAbortSession4XXHighThresholdAlarm` `DatapointsToAlarm` from `3` to `5`
<details>
- **Edge Cases**: Have edge cases been considered …

DCMAW-14348: Update AsyncAbortSession 4XX alarms

---

backend-api/src/functions/adapters/aws/sqs/sendMessageToSqs.test.ts
backend-api/src/functions/adapters/aws/sqs/sendMessageToSqs.ts
backend-api/src/functions/asyncAbortSession/asyncAbortSessionHandler.test.ts
backend-api/src/functions/asyncAbortSession/asyncAbortSessionHandler.ts
backend-api/src/functions/asyncAbortSession/handlerDependencies.ts
backend-api/src/functions/asyncIssueBiometricCredential/asyncIssueBiometricCredentialHandler.test.ts
backend-api/src/functions/asyncIssueBiometricCredential/asyncIssueBiometricCredentialHandler.ts
backend-api/src/functions/asyncIssueBiometricCredential/handlerDependencies.ts
backend-api/src/functions/testUtils/unitTestData.ts
test-resources/tests/api-tests/dequeueCredentialResult/dequeueCredentialResult.test.ts

DCMAW-14248
Changes
- Update `sendMessageToSqs` adapter to return the `MessageId` from the SQS response
- Update `IssueBiometricCredential` `COMPLETED` log to include the `MessageId` from the outbound SQS message response
- Update `AbortSession` `COMPLETED` log to include the `MessageId` from the outbound SQS message response
Fixes
- Add missing data to test-resources api tests
<details>
- **Security Considerations**: Are there any …

DCMAW-14248: Add MessageId to IssueBiometricCredential and AbortSession COMPLETED logs

---

backend-api/infra/resources/async/issueBiometricCredential/function.yaml
backend-api/infra/resources/async/vendorProcessingQueue/queue.yaml
backend-api/template.yaml
backend-api/tests/infra-tests/application.test.ts

DCMAW-14743
* This was causing API tests to fail in Build - it seems that in periods of low traffic, the duration of this lambda is typically well above 1000ms.
* The increase to the initial delay seconds is being retained, as this is unrelated to the timeout issue and can add value.
<details>
- **Testing**: Is the code well-tested with …

[DCMAW-14743] Revert changes to Vendor Processing Queue and Issue Biometric Credential timeouts

---

backend-api/infra/resources/async/vendorProcessingQueue/queue.yaml
backend-api/template.yaml

DCMAW-14734
<details>
- **Readability**: Is the code easy to understand for all team members, with clear naming and appropriate documentation?
- **Maintainability**: Is …

[DCMAW-14734] Reduce Vendor Processing Queue visibility timeout to 6

---

.github/workflows/job_test-suite.yml

DCMAW-12119
Move sonarqube steps to be straight after unit tests so it can use the coverage report produced by unit tests
<details>
- **Readability**: Is the code easy …

DCMAW-12199: move sonarqube steps to be just after unit test step

---

backend-api/infra/config/globals.yaml
backend-api/template.yaml

DCMAW-14912
* Hardcodes Dynatrace layer ARN - see [here](https://govukverify.atlassian.net/browse/DCP-5479) for context.
<details>
- **Readability**: Is the code easy …

[DCMAW-14912] Hardcode dynatrace layer ARN

---

backend-api/infra/resources/privateApi/credential/function.yaml
backend-api/infra/resources/privateApi/token/function.yaml
backend-api/template.yaml

Jira Ticket
[DCMAW-15481](https://govukverify.atlassian.net/browse/DCMAW-15481)
The Private API currently integrates directly to the lambda qualifier (arn:aws:lambda:eu-west-2::function:sandy-async-backend-token) and not to the live alias.
This is **part 3.** of a three step approach to remediate this:
1. Add a lambda permission enabling the Private API to invoke the lambda live alias #845 
1. Update the Private API to invoke with the live alias #846 
1. Remove the old lambda permission that allows the lambda qualifier above to be invoked by the Private API
This change also has the side benefit of ensuring the lambda can only be invoked by POST /async/token and POST /async/credential endpoints.
<details>
- **Functionality**: Does it meet the acceptance …

DCMAW-15481: remove legacy private api lambda permissions
