govuk-one-login/mobile-id-check-async

.github/workflows/async-credential-pull-req.yml, src/functions/asyncCredential/TokenService/tokenService.test.ts, src/functions/asyncCredential/TokenService/tokenService.ts, src/functions/asyncCredential/asyncCredentialHandler.test.ts, src/functions/asyncCredential/asyncCredentialHandler.ts, src/functions/asyncCredential/todo.md, src/functions/asyncToken/asyncTokenHandler.test.ts, src/functions/asyncToken/asyncTokenHandler.ts, src/functions/asyncToken/requestService/requestService.ts, src/functions/asyncToken/ssmService/ssmService.ts, src/functions/asyncToken/tokenService/tokenService.ts, src/functions/config.ts, src/functions/services/clientCredentialsService/clientCredentialsService.test.ts, src/functions/services/clientCredentialsService/clientCredentialsService.ts, src/functions/testUtils/mockRequest.ts, src/functions/types/clientCredentials.ts, src/functions/types/errorOrValue.ts, src/functions/types/jwt.ts, src/template.yaml
DCMAW-8264
Add request validation to check Authorization request header in the asyncCredential lambda.
Implements this design: https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/3917447301/Strategic+App+%7C+DCMAW-7690+%7C+Implementing+Client+Credentials+Grant+Flow+and+Asynchronous+CRI+credential+requests?search_id=c82aefcc-ef51-49e6-92d2-46ba3ade362d as part of the OAuth2.0 Client Credential Grant flow.
=> DCMAW-8264: Add validation for token claims

.github/workflows/async-credential-push-to-main.yml
DCMAW-8264
​
Adds a GHA workflow when there is a push to the main branch. There is branch protection enabled ensuring that only Pull Requests can update the main branch - i.e. this workflow will only run on result of merging a Pull Request.
To run a main branch Sonar scan.
=> DCMAW-8264: Create push to main GHA

src/functions/asyncCredential/asyncCredentialHandler.test.ts, src/functions/asyncCredential/asyncCredentialHandler.ts
Add request body validation in Async Credential lambda
Implements [this design](https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/3917447301/Strategic+App+%7C+DCMAW-7690+%7C+Implementing+Client+Credentials+Grant+Flow+and+Asynchronous+CRI+credential+requests?search_id=c82aefcc-ef51-49e6-92d2-46ba3ade362d) as part of the OAuth2.0 Client Credential Grant flow.
We have validated the following in this PR:
- `state`
- `sub`
- `client_id`
- `govuk_signin_journey_id`
The following have not yet been validated and will be in the next PR:
- `redirect_uri`
DCMAW-8264
=> DCMAW-8264: Implement request body validation in credential lambda

README.md
Removed Async-credential Pull Request CI badge from the README.
=> DCMAW-8264: Remove pull request ci badge from readme

.github/dependabot.yml
Dependabot scans the npm packages once a week on Thursday morning at 03:00. This has now been updated to run on Tuesday at 03:00
Running Tuesday morning allows us to see a free set of version bump PRs at the start of each sprint, rather than a random day in the middle of it.
DCMAW-9561. This change is just a part of the continious maintainence of this version-bump process, do not believe it requires a standalone ticket
=> DCMAW-9561: Update NPM version bump scan to run Tuesday

src/functions/asyncCredential/asyncCredentialHandler.test.ts, src/functions/asyncCredential/asyncCredentialHandler.ts, src/functions/asyncToken/asyncTokenHandler.test.ts, src/functions/asyncToken/asyncTokenHandler.ts, src/functions/services/clientCredentialsService/clientCredentialsService.test.ts, src/functions/services/clientCredentialsService/clientCredentialsService.ts
- Add validation to check the stored/registered `redirect_uri` is valid when a request is made to the `/async/token` endpoint and the `/async/credential` endpoint.
- Update `validate()` method on `ClientCredentialsService` to validate the registered `redirect_uri` and update method name to reflect that the validation is being done on the `/async/token` endpoint request data
- Add method to the `ClientCredentialsService` to validate the supplied `redirect_uri` from the `/async/credential` request data
=> DCMAW-8264: WIP - Add validation to check request redirect_uri and registered redirect_uri

src/functions/asyncCredential/asyncCredentialHandler.test.ts, src/functions/asyncCredential/asyncCredentialHandler.ts
- Added unit test for when the lambda parses the event body.
- Updated null check logic so it won't include an empty string in this check. Rationale is event.body will always be present in this type of request, this check is being done as typescript requires this before parsing data. An empty string isn't part of this check and therefore will fail at the parsing step.
Missed test case where the event body is not valid JSON. The logic is there to handle invalid JSON is there already.
I used the `invaldJsonCases` array so I could describe the value in the test output as opposed to stating the value itself, as I think this is easier to understand.
Using the array with descriptions of the value results in this output:
```
Given body contains invalid JSON
✓ Returns 400 status code with …
```
=> DCMAW-8264: Add missing JSON.parse test

src/functions/asyncCredential/asyncCredentialHandler.test.ts, src/functions/asyncCredential/asyncCredentialHandler.ts, src/functions/asyncCredential/recoverSessionService/dynamoDbClient.ts, src/functions/asyncCredential/recoverSessionService/recoverSessionService.test.ts, src/functions/asyncCredential/recoverSessionService/recoverSessionService.ts, src/functions/config.ts, src/package-lock.json, src/package.json
Create service to check if user already has a valid session, if so return success response with the `sub` from the `JAR` and "https://vocab.account.gov.uk/v1/credentialStatus": "pending"
Following tech design which is found on ticket: DCMAW-8264
=> DCMAW-8264: Create session recovery service for credential lambda

src/functions/asyncCredential/asyncCredentialHandler.test.ts, src/functions/asyncCredential/todo.md, src/functions/testUtils/mockJwt.ts
DCMAW-8264
​
Add functionality for generating mock JWTs for unit testing
Avoids the need to hardcode JWTs
Easier visibility of what each mock JWT is for
=> DCMAW-8264: Create jwt builder for tests

src/functions/asyncCredential/asyncCredentialHandler.test.ts, src/functions/asyncCredential/asyncCredentialHandler.ts, src/functions/asyncCredential/registeredLogs.ts
​DCMAW-8264
Logs when JWT claims are missing or do not pass validation https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/3917447301/Strategic+App+DCMAW-7690+Implementing+Client+Credentials+Grant+Flow+and+Asynchronous+CRI+credential+requests
Observability
=> DCMAW-8264: Log when jwt claims are invalid

src/functions/asyncCredential/asyncCredentialHandler.test.ts, src/functions/asyncCredential/asyncCredentialHandler.ts, src/functions/asyncToken/asyncTokenHandler.test.ts, src/functions/services/clientCredentialsService/clientCredentialsService.test.ts, src/functions/services/clientCredentialsService/clientCredentialsService.ts
​DCMAW-8265
Adds test coverage for when the supplied redirect_uri is registered in the ClientCredentials Array
Flagged by Sonar
=> DCMAW-8265: Add test coverage for valid redirect_uri

backend-api/src/functions/asyncCredential/asyncCredentialHandler.test.ts, backend-api/src/functions/asyncCredential/asyncCredentialHandler.ts, backend-api/src/functions/asyncCredential/registeredLogs.ts
​DCMAW-8264
Log when request body for the Credential lambda does not pass validation. This does not include validation against the stored client array in SSM.
Observability
=> DCMAW-8264: Log when request body is invalid

backend-api/src/functions/asyncCredential/asyncCredentialHandler.ts, backend-api/src/functions/asyncCredential/sessionService/sessionService.test.ts, backend-api/src/functions/asyncCredential/sessionService/sessionService.ts
​DCMAW-8264
Write `issuedOn` value into session
This value will be used when the lambda initially checks for any active sessions before creating a new session
=> DCMAW-8264: Write issuedOn field when creating new session

backend-api/src/functions/asyncCredential/asyncCredentialHandler.ts, backend-api/src/functions/services/events/eventService.test.ts, backend-api/src/functions/services/events/eventService.ts
​DCMAW-9802
Removed the client id field from TxMA events
TxMA have requested that this field should only be used for including the ID for external RPs (not IPVCore). TxMA have confirmed that this field is optional so removing it entirely,.
=> DCMAW-9802: Remove client id from txma events

backend-api/src/functions/asyncCredential/asyncCredentialHandler.test.ts, backend-api/src/functions/asyncCredential/asyncCredentialHandler.ts, backend-api/src/functions/asyncCredential/sessionService/sessionService.test.ts, backend-api/src/functions/asyncCredential/sessionService/sessionService.ts
​DCMAW-9802
- Refactors creating a session to reduce the length of the /credential Lambda by moving logic to the Session Service.
=> DCMAW-9802: Refactor session creation

.github/dependabot.yml
​DCMAW-9848
Updated dependabot config
package.json location has moved
[DCMAW-9848]: https://govukverify.atlassian.net/browse/DCMAW-9848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DCMAW-9848: Fix npm package.json path in dependabot config

backend-api/src/functions/asyncToken/asyncTokenHandler.ts, backend-api/src/functions/services/events/eventService.ts, backend-api/src/functions/services/events/tests/eventService.test.ts
​DCMAW-9906
The CLIENT_CREDENTIALS_TOKEN_ISSUED event is being registered with TxMA. This:
- Adds the client_id into the event
- Fixes the mock timestamp naming
Align to schema
=> DCMAW-9906: Fix token-issued txma event schema

.gitignore, backend-api/Dockerfile.test, backend-api/run-tests-locally.sh, backend-api/run-tests.sh, sonar-project.properties
DCMAW-9786
This change includes building out the test container to be used in the dev, build and staging deployments. This is a pre-requisite for creating a post-merge Github action, which will be included in a subsequent PR.
=> [DCMAW-9786] Add dev platform assets to enable testing in codebuild

.github/pull_request_template.md, .github/workflows/backend-api-push-to-main.yml, backend-api/template.yaml
​DCMAW-10013
- Pins the version of SAM CLI in the push-to-main action for the backend-api stack
- Addresses linting issues the latest version of the SAM CLI highlights
Fix pipeline and prevent future breaking changes
=> DCMAW-10013: pin sam cli version

backend-api/infra-tests/application.test.ts, backend-api/template.yaml
`LogGroupName` in `AsyncCredentialPrivateApiAccessLogs` resource updated
Resource name changed in this PR however as the LogGroupName of the resource did not change, we encounterd an error when deploying to main:
```
/aws/apigateway/mob async-backena private api-access-logs already exists in stack arn:aws: cloudfor mation:eu-west-2:21112 5300205: stack/mob async-backend/383028e0 -502f-11ef-8a42-0afd13 d555cd
```
Strategy is to update the `LogGroupName` temporarily and merge. Once a deployment is success I will raise another PR to revert the `LogGroupName`
=> DCMAW-10009: Temporarily update private api access logs LogGroupName

backend-api/infra-tests/application.test.ts, backend-api/template.yaml
​DCMAW-10009
- Reverted temporary change to private api access logs `LogGroupName`
Please note, this is not a complete revert of the previous PR(#97). A typo in the infra tests was also fixed in the previous PR and that change is remaining.
Resource name changed in this [PR](https://github.com/govuk-one-login/mobile-id-check-async/pull/96) however as the LogGroupName of the resource did not change, we encountered an error when deploying to main:
```
/aws/apigateway/mob async-backena private api-access-logs already exists in stack arn:aws: cloudfor mation:eu-west-2:21112 5300205: stack/mob async-backend/383028e0 -502f-11ef-8a42-0afd13 d555cd
```
Strategy is to update the `LogGroupName` temporarily and merge (done in #97). A deployment has now been successful so this PR is to revert the …
=> DCMAW-10009: Revert temporariy update to private api access logs LogGroupName

backend-api/package-lock.json, backend-api/package.json
​DCMAW-10071
- Added `micromatch` package to `overrides` block to address vulnerability in previous version to force version of `micromatch` to be at least `4.0.8`.
Dependabot found a vulnerability within the `micromatch` package. CVE:
https://nvd.nist.gov/vuln/detail/CVE-2024-4067
As this is an indirect dependency, I investigated whether upgrading the direct dependency would rectify the issue however the same, vulnerable version of `micromatch` was still in use therefore forcing minimum version in `overrides` block
Running `npm audit` now shows 0 vulnerabilities:
=> DCMAW-10071: Fix micromatch vulnerability - Backend API

infra/templates/dns-records/infra-test/package-lock.json, infra/templates/dns-records/infra-test/package.json, infra/templates/dns/infra-test/package-lock.json, infra/templates/dns/infra-test/package.json
​DCMAW-10071
- Created `overrides` block in `package.json` in both `infra/templates/dns/infra-test/` and `infra/templates/dns-records/infra-test`
-  Added `micromatch` package to overrides block to address vulnerability in previous version, forcing the version of `micromatch` to be at least `4.0.8`.
Dependabot found a vulnerability within the `micromatch` package. CVE:
https://nvd.nist.gov/vuln/detail/CVE-2024-4067
As this is an indirect dependency, I investigated whether upgrading the direct dependency would rectify the issue however the same, vulnerable version of `micromatch` was still in use therefore forcing minimum version in `overrides` block
Running `npm audit` now shows `micromatch` vulnerabilities has gone (unrelated `semver` vulnerability still showing):
From …
=> DCMAW-10071: Fix micromatch vulnerability - Infra

.github/workflows/backend-api-push-to-main.yml, .github/workflows/sts-mock-push-to-main.yml, infra/terraform/secure_pipelines/mob_sts_mock_pipeline.tf, infra/terraform/secure_pipelines/mob_sts_mock_tir.tf
Set up secure pipelines to deploy `sts-mock` in Dev and Build environments.
Create test image repository to store test Dockerfile. 
Create `sts-mock-push-to-main` workflow to kick off Dev and Build pipelines and push test Dockerfile to ECR.
I have commented out the jobs for pushing images to ECR for Dev and Build as no test Dockerfile currently exists within the repo.
Updated the workflow job names to reference their environment so their purpose is clearer when viewing the jobs on GitHub.
Ticket:
[DCMAW-8964](https://govukverify.atlassian.net/jira/software/c/projects/DCMAW/boards/438?selectedIssue=DCMAW-8964)
[DCMAW-8964]: https://govukverify.atlassian.net/browse/DCMAW-8964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DCMAW-8964] Set up infra to deploy sts-mock stack

.github/workflows/backend-api-push-to-main.yml
​DCMAW-9786
Pushes image before it is signed
Image needs to exist in ECR before it's signed
=> [DCMAW-9786] Push build backend api image before signing image

sts-mock/infrastructure-tests/application.test.ts, sts-mock/template.yaml
​DCMAW-8964
- Adds permission boundaries and role names to IAM roles
- Adds infra test to check the above is present for every IAM role in template
- `sam build` is currently failing in the pipeline to not having correct permissions, see thread [here](https://gds.slack.com/archives/C04RSBGJH6D/p1726047618614799)
=> DCMAW-8964: Adding permission boundaries and role names for STS Mock IAM roles

sts-mock/template.yaml
​DCMAW-8964
- Updated indentation of permissions boundary block, should be within parameters
Linting template now shows no errors
=> DCMAW-8964: Fixing parameters block indentation

sts-mock/template.yaml
​DCMAW-8964
- Creates new Globals section of template with Function property
- Add permission boundary to give correct permissions as detailed [here](https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3059908609/How+to+deploy+a+SAM+application+with+secure+pipelines#Support-permissions-boundary)
- Fix pipeline failure
=> DCMAW-8964:  Setting permissions boundary as a global function parameter for STS Mock

sts-mock/template.yaml
​DCMAW-8964
- Temporarily rename jwks access log s3 bucket
- sam deploy in pipeline says bucket already exists therefore will rename in this PR. Will revert name change in follow-up PR.
=> DCMAW-8964: Temporarily rename jwks access log s3 bucket

backend-api/template.yaml
​DCMAW-8456
Add the environment suffix to access log bucket name
S3 bucket names are globally unique.
=> DCMAW-8456: add environment suffix to s3 access bucket name

.github/workflows/backend-api-push-to-main.yml, .github/workflows/sts-mock-push-to-main.yml
​DCMAW-10100
Reverts `govuk-one-login/devplatform-upload-action`
Issue with current version block deployment. Reverting for the time being to unblock deployments
- [Pipeline failure](https://gds.slack.com/archives/C04RSBGJH6D/p1726216850516919)
- [Another team with a similar issue reporting it to dev-platform](https://gds.slack.com/archives/C02U78Y5J3H/p1726154783127229)
=> DCMAW-10100: Reverts govuk-one-login/devplatform-upload-action version in GitHub workflows

backend-api/src/functions/asyncToken/asyncTokenHandler.ts, backend-api/src/functions/services/events/eventService.ts, backend-api/src/functions/services/events/tests/eventService.test.ts
​DCMAW-9906
Removes client id from audit events
Agreed that this shouldn't be included in schema - https://github.com/govuk-one-login/event-catalogue/pull/206#discussion_r1757145424
=> DCMAW-9906: remove client-id from events

.github/workflows/sts-mock-push-to-main.yml
​DCMAW-10218
Rolls back `govuk-one-login/devplatform-upload-action` to the most recent version pinned in this repository (https://github.com/govuk-one-login/mobile-id-check-async/pull/118)
Bug in latest commit - https://gds.slack.com/archives/C02U78Y5J3H/p1726220823459709
=> DCMAW-10218: Roll back dev platform upload GHA bump

backend-api/package-lock.json, backend-api/package.json
- Adds `path-to-regexp` to `package.json` overrides block
- Forcing version `0.1.11` or above for `express` only due to compatibility
- There are higher major versions (6.X and 8.X are active) but not currently compatible with `express`. Forcing version 8.X for all other packages using `path-to-regexp`
- Updates express package which also uses `path-to-regexp`
Indirect dependency and direct package has not patched this yet. Therefore have added `path-to-regexp` to overrides so only patched versions of this can be used
Running `npm audit` shows there are no longer any vulnerabilities
- [DCMAW-10182](https://govukverify.atlassian.net/browse/DCMAW-10182)
[DCMAW-10182]: https://govukverify.atlassian.net/browse/DCMAW-10182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …
=> DCMAW-10182: Fixes path-to-regexp security vulnerability in backend-api

backend-api/src/functions/asyncCredential/asyncCredentialHandler.test.ts, backend-api/src/functions/asyncCredential/asyncCredentialHandler.ts, backend-api/src/functions/asyncCredential/configService/configService.ts, backend-api/src/functions/asyncCredential/sessionService/sessionService.ts, backend-api/src/functions/asyncCredential/sessionService/tests/sessionService.test.ts, backend-api/src/functions/tests/pact/dependencies/asyncCredentialDependencies.ts, backend-api/template.yaml
​DCMAW-10100
- Updates session service:
- `createSession` now uses epoch time in seconds for `timeToLive` field. 
- `getActiveSession` now compares current time in seconds to `timeToLive` field
- Updates environment variable for session duration to be in seconds rather than milliseconds
- Name change; `SESSION_DURATION_IN_MILLISECONDS` => `SESSION_DURATION_IN_SECONDS`
- Value changed from 3600000 => 3600
AWS docs state that field we use as the official `ttl` must be in seconds:
_"To use TTL, first enable it on a table and then define a specific attribute to store the TTL expiration timestamp. The timestamp must be stored in [Unix epoch time format](https://en.wikipedia.org/wiki/Unix_time) at the seconds granularity. Each time an item is created or updated, you can compute the expiration …
=> DCMAW-10100: Updates timeToLive field in session to be represented in seconds

backend-api/src/functions/asyncCredential/requestService/requestService.ts, backend-api/src/functions/services/utils/requestService.ts
​DCMAW-8229
- Extracts `getAuthorizationHeader` function to modularise code for multiple lambdas.
Sonar failed validation due to duplication when adding code for the activeSession lambda (#159). This PR is to move common code into a common directory.
=> DCAMW-8229: Refactor request service to extract common methods

backend-api/src/functions/asyncActiveSession/asyncActiveSessionHandler.test.ts, backend-api/src/functions/asyncActiveSession/asyncActiveSessionHandler.ts, backend-api/src/functions/asyncActiveSession/handlerDependencies.ts, backend-api/src/functions/asyncActiveSession/registeredLogs.ts, backend-api/src/functions/asyncActiveSession/requestService/requestService.ts
​DCMAW-8229
- Adds request service for lambda to consume, validates Authorization header and returns it to lambda
- Adds handler dependencies
- Adds registered logs
Building out link session
=> DCMAW-8229: Adds Auth header validation to asyncActiveSession lambda

infra/terraform/secure_pipelines/mob_async_backend_pl.tf, infra/terraform/secure_pipelines/mob_sts_mock_pipeline.tf
​DCMAW-8456
Update secure pipelines for async account to version 2.68.1
Comment out test image repository uri for sts-mock-pl as its not in use currently
=> [DCMAW-8456] Update secure pipelines version to 2.68.1

.github/workflows/sts-mock-pull-request.yml, sts-mock/template.yaml
Relates to ​DCMAW-8965
- Remove unnecessary `DependsOn` from the sts-mock SAM template
- Add `sam validate --lint` to GHA on pull request
- To ensure template is valid before merging
- To fix GHA failure
=> fix: remove DependsOn from sts-mock SAM template

.github/workflows/backend-api-push-to-main.yml, .github/workflows/sts-mock-push-to-main.yml
​DCMAW-XXXXX
Relates to https://github.com/govuk-one-login/mobile-id-check-async/pull/170
- Change `devplatform-upload-action` back to `6985ccbaa306e2320a8826252c922af65242b283`
- `b7994fb959f70cc1440295de9e823f317ffa197e` is broken
=> chore(DCMAW): revert devplatform-upload-action to older version

sts-mock/template.yaml
​DCMAW-10254
- Associate the STS mock Token function with the `devplatform-vpc`
- Remove some comments from the SAM template
- Rename some policies
Stack deployed to `dev` and tested by sending a POST request to `/token`:
- It is a security best practice to restrict access to the function
=> DCMAW-10254: add STS mock Token function to VPC

sts-mock/template.yaml
​DCMAW-10254
Relates to https://github.com/govuk-one-login/mobile-id-check-async/pull/177
Temporarily change `TokenFunctionRole` name from `${AWS::StackName}-token` to `${AWS::StackName}-token-2` - this change will be reverted in another PR
To fix CodePipeline failure
=> fix: change TokenFunctionRole name temporarily

infra/terraform/base_stacks/main.tf, infra/terraform/base_stacks/vpc.tf, sts-mock/src/token/tokenEncrypter/tokenEncrypter.ts, sts-mock/template.yaml
​DCMAW-10254
Relates to PR https://github.com/govuk-one-login/mobile-id-check-async/pull/177
**Infrastructure:**
- Allow communication with S3 and traffic outside VPC
**Token (sts-mock) Lambda - SAM template:**
- Reference `devplatform-vpc-AWSServicesEndpointSecurityGroupId` instead of creating a new one
- Remove `ENIPolicy` and `LogsPolicy` as these have been placed with AWSLambdaVPCAccessExecutionRole
**devplatform-vpc stack deployed to dev**:
**sts-mock stack deployed to dev:**
- VPC parameters had to be configured correctly in order for the Token function to work
=> DCMAW-10254: fix VPC configuration and Token VPC configuration

sts-mock/template.yaml, sts-mock/tests/infrastructure-tests/application.test.ts
Relates to [DCMAW-10254](https://govukverify.atlassian.net/browse/DCMAW-10254
)
Remove `sts-mock` from the STS mock API name as it's already part of the stack name.
Stack deployed and tested in `dev`:
`/token`
`/.well-known/jwks.json`
To stop `sts-mock` from being stated twice:
[DCMAW-10254]: https://govukverify.atlassian.net/browse/DCMAW-10254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: simplify STS mock API name

backend-api/src/functions/asyncActiveSession/requestService/requestService.ts, backend-api/src/functions/asyncCredential/requestService/requestService.ts, backend-api/src/functions/asyncCredential/tokenService/tests/tokenService.test.ts, backend-api/src/functions/asyncCredential/tokenService/tokenService.ts, backend-api/src/functions/services/utils/getBearerToken.ts
​DCMAW-8229
- Updated request service util file and function name to be more specific to what it does
- Updates variable name inside util func, `jwe` now is `token`
- Updates imports
- Updates tokenService to not split header as this is already done in util func
- Updates tokenService tests as func is no longer expecting token starting with the word bearer
In #183 we changed how a shared util works by returning the token already being split (i.e. not returning the token with the word Bearer at the start). The token service used by the Credential lambda was not expecting this and therefore started returning 500 responses.
This util function is used in the `asyncCredential` and `asyncActiveSession` lambdas.
Previously when calling credential endpoint we'd receive a 500. Ana found the …
=> DCMAW-8229: Update logic in shared util in request service

backend-api/template.yaml, backend-api/tests/infra-tests/application.test.ts, infra/terraform/base_stacks/vpc.tf, sts-mock/tests/infrastructure-tests/application.test.ts
​DCMAW-8229
- Add `VpcConfig` to Lambda functions and `VpcPolicy` to Lambda IAM Roles for:
- AsyncToken
- AsyncCredential
- AsyncActiveSession
- Jwks
- Add infra tests
Async backend and STS mock stacks were deployed to dev and tested:
Token & Credential
STS Mock Token & Active Session
- It is a security best practice to restrict access to functions
=> DCAMW-8229: Add Lambdas to VPC

backend-api/src/functions/asyncCredential/asyncCredentialHandler.ts, backend-api/src/functions/asyncToken/asyncTokenHandler.ts, backend-api/src/functions/services/events/eventService.ts, backend-api/tests/api-tests/clientCredentialsGrantFlow.test.ts, infra/terraform/base_stacks/vpc.tf, infra/terraform/secure_pipelines/mob_async_backend_pl.tf
​DCMAW-8389
Relates to PRs https://github.com/govuk-one-login/mobile-id-check-async/pull/201, https://github.com/govuk-one-login/mobile-id-check-async/pull/203 & https://github.com/govuk-one-login/mobile-id-check-async/pull/202
- Remove temporary log messages 
- Put  `mob_async_backend_pl.tf` and `vpc.tf` in alphabetical order
- The following infra changes introduced in the previous PRs liked above:
**mob_async_backend_pl.tf**
```
AllowedServiceOne = "EC2"
AllowedServiceTwo = "SQS"
AllowedServiceThree = "DynamoDB"
RunTestContainerInVPC = "True"
ProgrammaticPermissionsBoundary = "True"
```
**vpc.tf**
```
CloudFormationEndpointEnabled = "Yes"
LogsApiEnabled = "Yes"
```
- To allow API test to run in the VPC
=> DCMAW-8389: clean up changes introduced in previous PRs

backend-api/tests/api-tests/utils/apiInstance.ts
​DCMAW-8389
- Fix API tests so that `aws4Interceptor` is only used with the proxy API and not the others
- `aws4Interceptor` not required for public and private APIs
=> DCMAW-8389: use aws4Interceptor with proxy API only

backend-api/tests/api-tests/clientCredentialsGrantFlow.test.ts
​DCMAW-8389
- Fix API tests so that private API endpoints are invoked with `"Authorization"` instead of `"x-custom-auth"` in the header
=> DCMAW-8389: fix header when calling private API

backend-api/template.yaml, sts-mock/template.yaml
​DCMAW-10280
Move over the BE and sts-mock resources to the new async DNS certificates
To add additional DNS names for our new API resources
[See first PR for update SSM parameter for new certificate being referenced here](https://github.com/govuk-one-login/mobile-id-check-async/pull/172)
Dev stacks attached to new certificate:
BE on new certificate:
sts-mock on new certificate:
=> [DCMAW-10280] Set apis to use new async SSM parameter

backend-api/template.yaml, backend-api/tests/infra-tests/application.test.ts, infra/terraform/secure_pipelines/mob_async_backend_pl.tf
​DCMAW-10280
Remove the TestImageUriRepository value from the Staging pipeline parameters as we do not run the test container in the Staging pipeline.
Update sessions api rate limits to allow tests to run on sessions api
We don't run tests in Staging.
Test stage removed from pipeline:
=> [DCMAW-10280] Remove test stage from Staging pipeline

backend-api/template.yaml
​DCMAW-8229
- Remove `-temp` from DynamoDB table name
- `-temp` was only added temporarily to allow changes to be made to the resource in a separate PR
=> fix: change DynamoDB table name back to what it was

backend-api/template.yaml
​DCMAW-10280
As part of trying to fix deployments in Staging, renaming the Sessions Table temporarily to see if it will deploy in the Staging environment.
Because Staging deployments are failing due to the sessions table.
=> [DCMAW-10280] rename sessions table to see if it will fix deployments

backend-api/src/functions/asyncActiveSession/asyncActiveSessionHandler.test.ts, backend-api/src/functions/asyncActiveSession/handlerDependencies.ts, backend-api/src/functions/asyncActiveSession/tokenService/publicKeyGetter.ts, backend-api/src/functions/asyncActiveSession/tokenService/tests/mocks.ts, backend-api/src/functions/asyncActiveSession/tokenService/tests/tokenService.test.ts, backend-api/src/functions/asyncActiveSession/tokenService/tests/tokenVerifier.test.ts, backend-api/src/functions/asyncActiveSession/tokenService/tokenService.ts, backend-api/src/functions/asyncActiveSession/tokenService/tokenVerifier.ts, backend-api/src/functions/asyncCredential/tokenService/tests/tokenService.test.ts, backend-api/src/functions/testUtils/mockJwtBuilder.ts
​DCMAW-8229
- Extracted token verification logic into TokenVerifier class
- Updated handler and TokenService dependencies to include TokenVerifier
- Updated MockJWTBuilder
- Added new function for building a singed JWT to enable testing of TokenVerifier
- Amend JWT header property to be `typ` instead of `type`
- Updates asyncCredential lambda test to use new encoded header value to reflect change to header property key name
To create better separation of concerns within token signature verification and to simplify adding and updating tests.
=> DCMAW-8229: Extract token verification logic

backend-api/src/functions/adapters/kmsAdapter.ts, backend-api/src/functions/adapters/tests/kmsAdapter.test.ts, backend-api/src/functions/adapters/tests/mocks.ts, backend-api/src/functions/asyncActiveSession/jwe/jweDecrypter.ts, backend-api/src/functions/asyncActiveSession/jwe/tests/jweDecrypter.test.ts, backend-api/src/functions/testUtils/mockJwtBuilder.ts
​DCMAW-8229
**KMS Adapter**
Check the exception type thrown by the KMS Client. If of type `InvalidCiphertextException` or `IncorrectKeyException`, throw a custom exception `ClientError`, otherwise just re-throw the error caught.
**Mock JWT Builder**
* Delete unused methods
If the client sends an invalid JWE (e.g. one where the CEK has been encrypted with the wrong key or the encryption is invalid), we currently return a server error (500) to the client, which is incorrect as these clearly error client errors (400).
=> DCMAW-8229: check KMS error type

sts-mock/template.yaml, sts-mock/tests/infrastructure-tests/application.test.ts
​DCMAW-8229
Change STS API's `ApiBurstLimit` and `ApiRateLimit` to `10` in `build` (previously `0`)
Fix API tests failure in `build`
=> DCMAW-8229: fix API test failure in build

sts-mock/template.yaml
​DCMAW-10416
`ASYNC_BACKEND_BASE_URL` envVar value if no override
Pipeline failure. Analysis can be found [here](https://gds.slack.com/archives/C04RSBGJH6D/p1729590644183349)
In previous PR this was [incorrectly set](https://github.com/govuk-one-login/mobile-id-check-async/pull/233/files#diff-8c3781550792bb6cc5b2caec488972810b818b0999b7454ad6d79658d4c6c2dcR202), you can see that `sessions-` has been accidentally removed.
=> DCMAW-10416: Fixes ASYNC_BACKEND_BASE_URL envVar if no override

.github/workflows/backend-api-pull-request.yml, .github/workflows/backend-api-push-to-main.yml, .github/workflows/sts-mock-pull-request.yml, .github/workflows/sts-mock-push-to-main.yml
​DCMAW-10586
Pin workflows to `ubuntu-22.04` as our workflows are not entirely compatible with upcoming `ubuntu-latest` changes.
=> [DCMAW-10586] pin all workflows to ubuntu 22.04

infra/terraform/base_stacks/vpc.tf
DCMAW-8782
Update VPC to allow the Lambda function to call the Dynatrace API.
Updates the VPC template version used to the latest version.
To allow Dynatrace to work
=> [DCMAW-8782] Update vpc for Dynatrace config

backend-api/template.yaml, backend-api/tests/infra-tests/application.test.ts
​DCMAW-10875
* Sets global MemorySize to 512 for async backend Lambdas
* Adds infra test for the same
* The programme standard is to default to 512, as a sweet spot of cost and performance.
* Out active session Lambda was experiencing frequent timeouts in all environments, disrupting testing - upping the memory was found to eliminate this issue.
* Memory set to 512MB for all lambdas in deployed stack
* All API tests passing against deployed stack
=> [DCMAW-10875] Set global MemorySize to 512 for async backend Lambdas

backend-api/package-lock.json, backend-api/package.json, sts-mock/package-lock.json, sts-mock/package.json
DCMAW-10870
Fix workflow failure caused by this PR: https://github.com/govuk-one-login/mobile-id-check-async/commit/65e185e6f5aa6ea4a71b3e9b3d2f748ff7b33d81
=> DCMAW-10870: move esbuild back to dependencies

backend-api/package-lock.json, backend-api/package.json
​DCMAW-10822
- Updates `package.json` `resolutions` entry for `express/path-to-regexp` to ensure that minimum version of this indirect dependancy will be `0.1.12`. 
Versions < `0.1.12` have vulnerability, see [here](https://github.com/pillarjs/path-to-regexp/security/advisories/GHSA-rhx6-c78j-4q9w)
Running `npm audit` shows 0 vulnerabilities
=> DCMAW-10822: Bumps path-to-regexp (indirect dep) to non vulnerable version

backend-api/template.yaml, backend-api/tests/infra-tests/application.test.ts
​DCMAW-8266
* Creates high and low threshold 4/5XX alarms for /async/credential endpoint. These will ensure that we, and live support, are notified for persistent issues with this endpoint.
* All four alarms are currently set to notify the warnings channel, with the high threshold alarms to be promoted to alerts on a future ticket.
* Updates infra tests accordingly
_The evidence provided here indicates that each alarm notifies slack correctly. To properly evidence that each alarm is configured with the correct conditions, please inspect the template.yaml, or view the alarms in the Cloudwatch console._
I have updated our [warning](https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/4800446694/Alarms+Runbook+Warnings) and [critical](https://govukverify.atlassian.net/wiki/spaces/DCMAW/p …
=> [DCMAW-8266] Create 4/5XX alarms for /async/credential

.github/workflows/backend-api-pull-request.yml, .github/workflows/backend-api-push-to-main.yml, .github/workflows/sts-mock-pull-request.yml, .github/workflows/sts-mock-push-to-main.yml, .github/workflows/test-resources-pull-request.yml, .github/workflows/test-resources-push-to-main.yml
​DCMAW-10904
Switch from `sonarsource/sonarcloud-github-action` to `sonarsource/sonarqube-scan-action`.
`sonarsource/sonarcloud-github-action` has been [deprecated](https://github.com/SonarSource/sonarcloud-github-action) and replaced by the pre-existing `sonarsource/sonarqube-scan-action`. This is a "drop-in replacement".
v4.2.1 is the latest version right now: https://github.com/SonarSource/sonarqube-scan-action/releases/tag/v4.2.1
=> DCMAW-10904: Switch sonarcloud-github-action for sonarqube-scan-action

.github/CODEOWNERS
​DCMAW-10882
Updated CODEOWNERS with new GitHub Team `@govuk-one-login/mobile-id-check-sre`. Code change means `@govuk-one-login/mobile-leads` can approve if SREs not available to approve.
Approvals are needed for code changes in .github dir and in any changes to template.yaml or dockerfiles.
This change was brought in so SREs must approve platform related changes in async. Can be approved by team leads if SREs not available.
=> [DCMAW-10882] update CODEOWNERS to require SRE approvals before merging PRs

backend-api/template.yaml, backend-api/tests/infra-tests/application.test.ts
Reroutes the traffic for the Session API through the cloudfront distribution stack. The CF DIstribution template is provided by Dev Platform and is now a requirement for the backend api stack in all instances. 
Changes: 
- `${VANITY_URL}` (i.e. `sessions-mob-async-backend.review-b-backend.dev.account.gov.uk`) now points to the cloudfront distribution domain
- Creates the `origin.${VANITY_URL}` route53 record which targets the sessions api gateway domain name. 
- Attaches the origin protection waf to ensure all traffic is passing through the cloudfront distribution. 
- Preemptively adds the tag `FMSRegionalPolicy: false` to exclude the api gateway stage from the automated WAF association and preserve the origin protection WAF.
Test: 
- Deployed a backend stack `douglast-async-backend` …
=> [DCMAW-10899] Async CloudFront | Route backend traffic through the cloudfront distribution

backend-api/template.yaml, backend-api/tests/infra-tests/application.test.ts
​DCMAW-11004
* Defines client registry secret path separately in each environment, instead of assuming the same path structure
* Updates Lambda execution role policy to refer to this path for resource
* Updates infra tests accordingly
* This is to align with what was done on DCMAW-10625 for biometric submitter keys. The rationale is that it gives us the flexibility to vary the path pattern in different environments should we want to (e.g. having a different path structure in production).
=> [DCMAW-11004] Define client registry secret path separately per environment

test-resources/package-lock.json, test-resources/package.json
​DCMAW-11032
- Bumps the backend-version group with 6 updates in the /test-resources directory:
| Package | From | To |
| --- | --- | --- |
| [@aws-sdk/client-dynamodb](https://github.com/aws/aws-sdk-js-v3/tree/HEAD/clients/client-dynamodb) | `3.709.0` | `3.726.1` |
| [@aws-sdk/util-dynamodb](https://github.com/aws/aws-sdk-js-v3/tree/HEAD/packages/util-dynamodb) | `3.709.0` | `3.726.1` |
| [@eslint/js](https://github.com/eslint/eslint/tree/HEAD/packages/js) | `9.17.0` | `9.18.0` |
| [eslint](https://github.com/eslint/eslint) | `9.17.0` | `9.18.0` |
| [typescript](https://github.com/microsoft/TypeScript) | `5.7.2` | `5.7.3` |
| [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/typescript-eslint) | `8.19.1` | `8.20.0` |
- …
=> DCMAW-11032: Update packages

backend-api/src/functions/asyncBiometricToken/getBiometricToken/getBiometricToken.test.ts, backend-api/src/functions/asyncBiometricToken/getBiometricToken/getBiometricToken.ts, backend-api/src/functions/common/logging/LogMessage.ts, backend-api/src/functions/services/http/sendHttpRequest.ts, backend-api/template.yaml
- Adds functionality to `getBiometricToken()` to send request to ReadID's `/token` endpoint with `submitterKey` to retrieve biometric access token
- Adds `POST` functionality in `sendHttpRequest()`
- Updates `template.yaml` to use v2 of ReadID mock
- Adds logs when making request to ReadID for biometric access token:
- `MOBILE_ASYNC_BIOMETRIC_TOKEN_GET_BIOMETRIC_TOKEN_FROM_READID_ATTEMPT`
- `level: "debug"` - will only appear in `dev`
- `MOBILE_ASYNC_BIOMETRIC_TOKEN_GET_BIOMETRIC_TOKEN_FROM_READID_FAILURE`
-  `level: "error"` - will appear in all environments
- `MOBILE_ASYNC_BIOMETRIC_TOKEN_GET_BIOMETRIC_TOKEN_FROM_READID_SUCCESS`
- `level: "debug"` - will only appear in `dev`
ReadID host a `/token` endpoint. This used for exchanging the submitter access key for a temporary access key …
=> DCMAW-10829: Get biometric access token from ReadID

backend-api/template.yaml, backend-api/tests/infra-tests/application.test.ts
​DCMAW-11079
- Change rate limits/burst limits from 0 for Private APIgw/Proxy APIgw and Sessions APIgw.
- Changing reserved lambda concurrency from 0 to 15
Testing the integration with Mobile Platform requires the Proxy API, Private API and Sessions API for creating a session, providing STS the well-known endpoint and resuming the session.
=> DCMAW-11079: Open up Staging for testing

backend-api/src/functions/asyncActiveSession/tokenService/publicKeyGetter.ts, backend-api/src/functions/asyncActiveSession/tokenService/tests/publicKeyGetter.test.ts, backend-api/src/functions/asyncBiometricToken/getBiometricToken/getBiometricToken.test.ts, backend-api/src/functions/asyncBiometricToken/getBiometricToken/getBiometricToken.ts, backend-api/src/functions/services/http/sendHttpRequest.ts, backend-api/src/functions/services/http/tests/sendHttpRequest.test.ts
- sendHttpRequest:
- Updates retry policy with exponential backoff and full jitter
- Updates interface to use Result pattern after discussion feedback [here](https://github.com/govuk-one-login/mobile-id-check-async/pull/337#discussion_r1918082211)
- Updates functions that consume sendHttpRequest as interface has changed:
- getBiometricToken
- publicKeyGetter (I made 2 additional changes listed below here we can revert if we want as minimal change as possible here):
- Updated func in publicKeyGetter to use the Result pattern instead of throwing errors some of the time [cb1e74c2c47ae5847b9ca6db848c01bebd040a33](https://github.com/govuk-one-login/mobile-id-check-async/pull/344/commits/cb1e74c2c47ae5847b9ca6db848c01bebd040a33)
- Updated publicKeyGetter to handle parsing error explicitly …
=> DCMAW-10829: Enhances http request retry strategy with exponential backoff and full jitter     

backend-api/README.md, backend-api/openApiSpecs/async-public-spec.yaml, backend-api/src/functions/jwks/jwksBuilder/jwksBuilder.ts, backend-api/src/functions/jwks/jwksBuilder/tests/jwksBuilder.test.ts, backend-api/src/functions/jwks/jwksBuilder/tests/mocks.ts, backend-api/src/functions/jwks/jwksUploader/tests/jwksUploader.test.ts, backend-api/src/functions/types/jwks.ts, backend-api/template.yaml, backend-api/tests/infra-tests/application.test.ts, sts-mock/src/token/tokenEncrypter/tests/tokenEncrypter.test.ts
​DCMAW-11093
Change algorithm in the JSON web key object for the encryption key from `RS256` to `RSA-OAEP-256`.
To align with both the spec: https://datatracker.ietf.org/doc/html/rfc7518#section-4.1 (`RSA256` is not a valid encryption algorithm) and the STS requirements: https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/3844964353/Strategic+App+App+calls+a+protected+service#Service-Token-encryption
=> DCMAW-11093: Update encryption algorithm for public encryption key 

backend-api/openApiSpecs/async-public-spec.yaml, backend-api/src/functions/adapters/tests/dynamoDbAdapter.test.ts, backend-api/src/functions/adapters/tests/getSecretsFromParameterStore.test.ts, backend-api/src/functions/asyncBiometricToken/asyncBiometricTokenHandler.test.ts, backend-api/src/functions/asyncBiometricToken/asyncBiometricTokenHandler.ts, backend-api/src/functions/asyncBiometricToken/getBiometricToken/getBiometricToken.test.ts, backend-api/src/functions/common/lambdaResponses.ts, backend-api/tests/api-tests/biometricToken.test.ts, backend-api/tests/testUtils/matchers.ts
​DCMAW-10831
* Updates biometric token handler to return 200 response with biometric access token from vendor, and generated opaque ID
* Updates associated tests
* Updates OpenAPI spec to reflect latest response fields
* The mobile app will use the access token and opaque ID to start a biometric session with the vendor.
=> [DCMAW-10831] /async/biometricToken returns 200 with biometric access token and opaque ID

sts-mock/run-tests.sh
​DCMAW-11057
Updates sts-mock `run-tests.sh` file to correctly `cd` into the sts-mock directory
Tests failing in pipeline because the tests were running in the wrong directory
=> DCMAW-11057: sts-mock update tests to use absolute path

backend-api/infra/api/proxy.yaml, backend-api/infra/api/sessions.yaml, backend-api/infra/parent.yaml, backend-api/template.yaml, backend-api/tests/infra-tests/application.test.ts, sts-mock/template.yaml
[​DCMAW-11018](https://govukverify.atlassian.net/browse/DCMAW-10844)
Uses wildcard cert and original domain name format for development stacks and new certs and domain name format for non development stacks. (Due to hard domain name length limits set by AWS - 64 chars)
https://github.com/govuk-one-login/mobile-id-check-async/pull/357
https://github.com/govuk-one-login/mobile-id-check-async-infra/pull/20
https://github.com/govuk-one-login/mobile-id-check-readid-mock/pull/20
=> [DCMAW-11018] update domain name formats

sts-mock/infra/parent.yaml, sts-mock/template.yaml
​DCMAW-11006
This is a forward fix to amend a pipeline failure caused by https://github.com/govuk-one-login/mobile-id-check-async/pull/373
=> DCMAW-11006: Update DevelopmentStack condition in BE .yaml file

sts-mock/tests/api-tests/dequeue/utils/apiTestHelpers.ts
​DCMAW-11006
The logs in CodeBuild indicate that the setup steps to create an active session are not working: note SESSION#undefined. We would expect to see a `sessionId` in place of the `undefined`.
Adding logs to help debug the test failures.
`Only found 0 events for pkPrefix=SESSION#undefined and skPrefix=TXMA#EVENT_NAME#DCMAW_ASYNC_CRI_START. Expected to find at least 1 events.`
Adds logging for API instance URLs, response bodies and status codes.
Tested that the outputs appear in the console logs of my laptop. ✅
=> DCMAW-11006: Add temporary logging for STS api tests

backend-api/infra/parent.yaml, backend-api/template.yaml, backend-api/tests/infra-tests/application.test.ts
DCMAW-11006
The STS URL used in the activeSession lambda to validate the issuer claim is incorrect. It should point to the STS API - the test-resources domain doesn't exist.
activeSession lambda logs highlighting the issue:
Correct domain:
=> DCMAW-11006: Update STS URL in lower envs

.github/dependabot.yml
DCMAW-11006: Removes duplicate block in dependabot.yml config file.
=> DCMAW-11006: remove duplicate dependabot directory

.github/CODEOWNERS
​DCMAW-11492
- Removes the `govuk-one-login/mobile-id-check` team from the Codeowners file.  This team is being deprecated following the wider ID Check team split: https://github.com/govuk-one-login/configuration/pull/783
- Ensures files that don't require SRE approval require a backend approval
=> DCMAW-11492: Update codeowners file to enforce more fine-grained permissions

backend-api/infra/api/private.yaml, backend-api/infra/parent.yaml, backend-api/template.yaml, backend-api/tests/infra-tests/application.test.ts
[​DCMAW-11530](https://govukverify.atlassian.net/browse/DCMAW-11530)
- Adds mapping to provide IPV Core VPC endpoint ID for each environment
- Adds condition to only integrate with IPV Core when environment is staging (to be rolled out to int and prod)
- Updates the private API resource policy to whitelist VPCe
- Updates the private API settings to include VPCe ID
- Update infra tests accordingly
To integrate with IPV Core
Screenshot of private API settings including VPCe (testing in dev env)
Screenshot of private API resource policy showing whitelisted VPCe (testing in dev)
=> DCMAW-11530: allow IPVCore VPCe to invoke private API

backend-api/infra/parent.yaml, backend-api/template.yaml, backend-api/tests/infra-tests/template.test.ts, test-resources/infra/parent.yaml, test-resources/template.yaml, test-resources/tests/infrastructure-tests/template.test.ts
​DCMAW-11107
There is a resource in the `parent.yaml` file to please different linting tools (particularly WebStorm). Without this the tools complain indicating that the cloudformation template is missing a Resource. 
Updated the condition that ensures this resource never deploys by tricking SAM; SAM doesn't evaluate instrinsic Cloudformation values/functions so does not realise this condition always equates to false. 
Flakey pre-merge pipelines
=> DCMAW-11107: Fix flakey sam validate --lint failure

backend-api/generate_env_file.sh, backend-api/infra/parent.yaml, backend-api/run-tests-locally.sh, backend-api/run-tests.sh, backend-api/template.yaml, backend-api/tests/api-tests/biometricToken.test.ts, backend-api/tests/api-tests/clientCredentialsGrantFlow.test.ts, backend-api/tests/api-tests/utils/apiInstance.ts, backend-api/tests/api-tests/utils/apiTestHelpers.ts, backend-api/tests/infra-tests/application.test.ts, backend-api/tests/infra-tests/helpers/mappings.ts, helper-scripts/deploy_backend.sh
​DCMAW-11007
- Adds TxMA event assertions to happy path API tests for:
- POST /async/token
- POST /async/biometricToken
- Adds test functions to the backend-api directory
- `getEventsApiInstance()`
- `pollForEvents()`
- Function to check if an event was created in the last 60 seconds
- Adds Events API URL to the backend for testing
- Adds Events env var to deploy and test scripts
=> DCMAW-11007: Add TxMA event happy path assertions to backend API test

backend-api/src/functions/asyncFinishBiometricSession/asyncFinishBiometricSessionHandler.test.ts, backend-api/src/functions/asyncFinishBiometricSession/asyncFinishBiometricSessionHandler.ts, backend-api/src/functions/services/events/tests/eventService.test.ts, backend-api/src/functions/services/events/types.ts, backend-api/src/functions/testUtils/unitTestData.ts, test-resources/src/functions/dequeue/getEvent.ts
- Writes `DCMAW_ASYNC_APP_END` in `async/finishBiometricSession` when request received with valid session information
- If event fails to write, return `500 Internal server error` response
- Adds `DCMAW_ASYNC_APP_END` event to dequeue lambda `getEvents` list so it can be picked up and API tested (see below re the API test)
- I have not added an API test for this change as we are covering the happy path API under this ticket. This requirement has been split into a different ticket as we want to have a dev discussion re the shape of this happy with API test.
You'll see I haven't used a helper function in this lambda for this event. My thinking was the two main things this lambda does is write the vendor processing message, and write the app end event, therefore I don't mind having these two …
=> DCMAW-11113: Updates finishBiometricSession to write ASYNC_APP_END TxMA event

backend-api/src/functions/asyncFinishBiometricSession/asyncFinishBiometricSessionHandler.test.ts, backend-api/src/functions/asyncFinishBiometricSession/asyncFinishBiometricSessionHandler.ts, backend-api/src/functions/common/lambdaResponses.ts, backend-api/tests/api-tests/biometricToken.test.ts, backend-api/tests/api-tests/clientCredentialsGrantFlow.test.ts, backend-api/tests/api-tests/finishBiometricSession.test.ts, backend-api/tests/api-tests/utils/apiTestHelpers.ts
- Updates `finishBiometricSession` to return `200 OK` response
- Updates `okResponse` function to cater for when the `response` `body` is empty
- Adds API test for `200` response, including assertion on the `DCMAW_ASYNC_APP_END` TxMA event
- API test helpers
- Removes duplication in API test helpers that got a `sessionId`
- Regarding the `sessionId` methods, the main one used was doing too much as it was creating a session with a sub and returning a sessionId, I have made it so a test will use a bespoke function for each step so it is clearer. 
- Updated biometricToken api tests to use new helper functions where appropriate
- Minor structural updates to finishBiometricSession API tests (beforeAll() and then only assertions in the it which is the pattern we are currently using)
Ongoing …
=> DCMAW-11115: Updates finishBiometricSession to return 200 OK response

backend-api/infra/api/private.yaml, backend-api/template.yaml, backend-api/tests/infra-tests/application.test.ts
​DCMAW-11501
Change log group name so we can update it in [pull request here](https://github.com/govuk-one-login/mobile-id-check-async/pull/477)
We are going to change the logical ID and it will create a new resource log group before deleting the old one, so we need to change the log group name otherwise the stack update will fail.
=> DCMAW-11501 Update log group name so it can revert back in the other PR

backend-api/infra/api/private.yaml, backend-api/infra/api/proxy.yaml, backend-api/infra/api/sessions.yaml, backend-api/infra/functions/activeSession.yaml, backend-api/infra/functions/biometricToken.yaml, backend-api/infra/functions/credential.yaml, backend-api/infra/functions/finishBiometricSession.yaml, backend-api/infra/functions/jwks.yaml, backend-api/infra/functions/proxy.yaml, backend-api/infra/functions/token.yaml, backend-api/infra/functions/txmaEvent.yaml, backend-api/infra/parent.yaml, backend-api/template.yaml, backend-api/tests/infra-tests/application.test.ts
​[DCMAW-11501](https://govukverify.atlassian.net/browse/DCMAW-11501)
Set up Subscription Filters to forward logs to CSLS in Build and above environments.
Subscription Filters will deploy in Build for proxy resources using DeployProxyCsls condition.
Add a test to check that all Cloudwatch log groups have an associated filter.
Provide DestinationArn using mapping.
[DCMAW-11501]: https://govukverify.atlassian.net/browse/DCMAW-11501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DCMAW-11501] Set up CSLS logging 

test-resources/infra/parent.yaml, test-resources/infra/sts-mock/token/function.yaml, test-resources/template.yaml, test-resources/tests/infrastructure-tests/application.test.ts
Reverts govuk-one-login/mobile-id-check-async#709
=> Revert "DCMAW-13943: Update rate limits and reserved concurrency for STS Mock /token endpoint"

backend-api/src/functions/asyncBiometricToken/asyncBiometricTokenHandler.test.ts, backend-api/src/functions/asyncBiometricToken/asyncBiometricTokenHandler.ts, backend-api/src/functions/services/events/eventService.ts, backend-api/src/functions/services/events/tests/eventService.test.ts, backend-api/src/functions/services/events/types.ts
DCMAW-14562
This change is required to improve consistency in TxMA event streams for user journeys
involving biometric token issuance.  Currently TCIF ops can use the field `opaque_id` in
event `DCMAW_ASYNC_BIOMETRIC_TOKEN_ISSUED` when analysing v1 user journeys,
but not v2 as it isn't emitted.
A bit of plumbing is needed in this change to ensure the opaque ID allocated at the start of
the biometric credential is passed through to the point the Event service is called.
<details>
- **Personally Identifiable …
=> [DCMAW-14562] Emit `opaque_id` in DCMAW_ASYNC_BIOMETRIC_TOKEN_ISSUED event.

backend-api/tests/api-tests/utils/apiTestHelpers.ts, test-resources/openApiSpecs/test-resources-spec.yaml, test-resources/tests/api-tests/dequeueCredentialResult/dequeueCredentialResult.test.ts, test-resources/tests/api-tests/dequeueEvents/dequeueEvents.test.ts
DCMAW-15069
* Limits events API query to 50 results.
* Updates error handling for event/credentialResult polling in API tests to error on malformed 2xx responses
The test in question (for the TOKEN_ISSUED TxMA event) would only fail when the underlying query returned 1000 or more items. On further investigation, Axios was not unmarshalling the response to an array in this scenario, and we were treating this as an empty array and retrying until we hit the timeout. It turns out that the API was returning invalid JSON, with a trailing `,` after the last item in the array. This is because VTL (the templating language used to generate the response in the API Gateway response mapping) will [only iterate over a maximum of 1000 items in an …
=> [DCMAW-15069] Limit events API query to 50 items

backend-api/infra/resources/common/alarms.yaml, backend-api/template.yaml, backend-api/tests/infra-tests/application.test.ts
DCMAW-14761
* Defines three new alarms (one per document type) capturing a drop in the percentage of VCs issued after the first call to ReadID. These alarms fire when, in two of the past five hours, there have been at least 5 VCs issued for that document type, and the percentage of these that were issued on the first attempt is below the threshold (90% for passports and driving licences, 75% for BRPs). **Please see the ticket for the rationale for this configuration.**
* Updates infra tests
<details>
- **Personally …
=> [DCMAW-14761] Define biometric session not ready alarms per document type

backend-api/infra/resources/privateApi/credential/function.yaml, backend-api/infra/resources/privateApi/token/function.yaml, backend-api/template.yaml
DCMAW-15481
The Private API currently integrates directly to the lambda qualifier (arn:aws:lambda:eu-west-2:<accountId>:function:sandy-async-backend-token) and **not** to the live alias.
This is **part 1.** of a three step approach to remediate this:
1. Add a lambda permission enabling the Private API to invoke the lambda `live` alias
2. Update the Private API to integrate with the `live` alias
3. Remove the old lambda permission that allows the lambda qualifier above to be invoked by the Private API
This change also has the side benefit of ensuring the lambda can only be invoked by `POST /async/token` and `POST /async/credential` endpoints.
<details>
- …
=> DCMAW-15481: Add dormant permission for private api to invoke lambda alias
